AL = Estado.find_by_sigla("AL")
AL.cidades.create(
  [
    { nome:  "Água Branca" },
    { nome:  "Anadia" },
    { nome:  "Arapiraca" },
    { nome:  "Atalaia" },
    { nome:  "Barra de Santo Antônio" },
    { nome:  "Barra de São Miguel" },
    { nome:  "Batalha" },
    { nome:  "Belém" },
    { nome:  "Belo Monte" },
    { nome:  "Boca da Mata" },
    { nome:  "Branquinha" },
    { nome:  "Cacimbinhas" },
    { nome:  "Cajueiro" },
    { nome:  "Campestre" },
    { nome:  "Campo Alegre" },
    { nome:  "Campo Grande" },
    { nome:  "Canapi" },
    { nome:  "Capela" },
    { nome:  "Carneiros" },
    { nome:  "Chã Preta" },
    { nome:  "Coité do Nóia" },
    { nome:  "Colônia Leopoldina" },
    { nome:  "Coqueiro Seco" },
    { nome:  "Coruripe" },
    { nome:  "Craíbas" },
    { nome:  "Delmiro Gouveia" },
    { nome:  "Dois Riachos" },
    { nome:  "Estrela de Alagoas" },
    { nome:  "Feira Grande" },
    { nome:  "Feliz Deserto" },
    { nome:  "Flexeiras" },
    { nome:  "Girau do Ponciano" },
    { nome:  "Ibateguara" },
    { nome:  "Igaci" },
    { nome:  "Igreja Nova" },
    { nome:  "Inhapi" },
    { nome:  "Jacaré dos Homens" },
    { nome:  "Jacuípe" },
    { nome:  "Japaratinga" },
    { nome:  "Jaramataia" },
    { nome:  "Jequiá da Praia" },
    { nome:  "Joaquim Gomes" },
    { nome:  "Jundiá" },
    { nome:  "Junqueiro" },
    { nome:  "Lagoa da Canoa" },
    { nome:  "Limoeiro de Anadia" },
    { nome:  "Maceió" },
    { nome:  "Major Isidoro" },
    { nome:  "Mar Vermelho" },
    { nome:  "Maragogi" },
    { nome:  "Maravilha" },
    { nome:  "Marechal Deodoro" },
    { nome:  "Maribondo" },
    { nome:  "Mata Grande" },
    { nome:  "Matriz de Camaragibe" },
    { nome:  "Messias" },
    { nome:  "Minador do Negrão" },
    { nome:  "Monteirópolis" },
    { nome:  "Murici" },
    { nome:  "Novo Lino" },
    { nome:  "Olho d'Água das Flores" },
    { nome:  "Olho d'Água do Casado" },
    { nome:  "Olho d'Água Grande" },
    { nome:  "Olivença" },
    { nome:  "Ouro Branco" },
    { nome:  "Palestina" },
    { nome:  "Palmeira dos Índios" },
    { nome:  "Pão de Açúcar" },
    { nome:  "Pariconha" },
    { nome:  "Paripueira" },
    { nome:  "Passo de Camaragibe" },
    { nome:  "Paulo Jacinto" },
    { nome:  "Penedo" },
    { nome:  "Piaçabuçu" },
    { nome:  "Pilar" },
    { nome:  "Pindoba" },
    { nome:  "Piranhas" },
    { nome:  "Poço das Trincheiras" },
    { nome:  "Porto Calvo" },
    { nome:  "Porto de Pedras" },
    { nome:  "Porto Real do Colégio" },
    { nome:  "Quebrangulo" },
    { nome:  "Rio Largo" },
    { nome:  "Roteiro" },
    { nome:  "Santa Luzia do Norte" },
    { nome:  "Santana do Ipanema" },
    { nome:  "Santana do Mundaú" },
    { nome:  "São Brás" },
    { nome:  "São José da Laje" },
    { nome:  "São José da Tapera" },
    { nome:  "São Luís do Quitunde" },
    { nome:  "São Miguel dos Campos" },
    { nome:  "São Miguel dos Milagres" },
    { nome:  "São Sebastião" },
    { nome:  "Satuba" },
    { nome:  "Senador Rui Palmeira" },
    { nome:  "Tanque d'Arca" },
    { nome:  "Taquarana" },
    { nome:  "Teotônio Vilela" },
    { nome:  "Traipu" },
    { nome:  "União dos Palmares" },
    { nome:  "Viçosa" }
  ]
)