CE = Estado.find_by_sigla("CE")
CE.cidades.create(
  [
  { nome:  "Abaiara" },
  { nome:  "Acarape" },
  { nome:  "Acaraú" },
  { nome:  "Acopiara" },
  { nome:  "Aiuaba" },
  { nome:  "Alcântaras" },
  { nome:  "Altaneira" },
  { nome:  "Alto Santo" },
  { nome:  "Amontada" },
  { nome:  "Antonina do Norte" },
  { nome:  "Apuiarés" },
  { nome:  "Aquiraz" },
  { nome:  "Aracati" },
  { nome:  "Aracoiaba" },
  { nome:  "Ararendá" },
  { nome:  "Araripe" },
  { nome:  "Aratuba" },
  { nome:  "Arneiroz" },
  { nome:  "Assaré" },
  { nome:  "Aurora" },
  { nome:  "Baixio" },
  { nome:  "Banabuiú" },
  { nome:  "Barbalha" },
  { nome:  "Barreira" },
  { nome:  "Barro" },
  { nome:  "Barroquinha" },
  { nome:  "Baturité" },
  { nome:  "Beberibe" },
  { nome:  "Bela Cruz" },
  { nome:  "Boa Viagem" },
  { nome:  "Brejo Santo" },
  { nome:  "Camocim" },
  { nome:  "Campos Sales" },
  { nome:  "Canindé" },
  { nome:  "Capistrano" },
  { nome:  "Caridade" },
  { nome:  "Cariré" },
  { nome:  "Caririaçu" },
  { nome:  "Cariús" },
  { nome:  "Carnaubal" },
  { nome:  "Cascavel" },
  { nome:  "Catarina" },
  { nome:  "Catunda" },
  { nome:  "Caucaia" },
  { nome:  "Cedro" },
  { nome:  "Chaval" },
  { nome:  "Choró" },
  { nome:  "Chorozinho" },
  { nome:  "Coreaú" },
  { nome:  "Crateús" },
  { nome:  "Crato" },
  { nome:  "Croatá" },
  { nome:  "Cruz" },
  { nome:  "Deputado Irapuan Pinheiro" },
  { nome:  "Ererê" },
  { nome:  "Eusébio" },
  { nome:  "Farias Brito" },
  { nome:  "Forquilha" },
  { nome:  "Fortaleza" },
  { nome:  "Fortim" },
  { nome:  "Frecheirinha" },
  { nome:  "General Sampaio" },
  { nome:  "Graça" },
  { nome:  "Granja" },
  { nome:  "Granjeiro" },
  { nome:  "Groaíras" },
  { nome:  "Guaiúba" },
  { nome:  "Guaraciaba do Norte" },
  { nome:  "Guaramiranga" },
  { nome:  "Hidrolândia" },
  { nome:  "Horizonte" },
  { nome:  "Ibaretama" },
  { nome:  "Ibiapina" },
  { nome:  "Ibicuitinga" },
  { nome:  "Icapuí" },
  { nome:  "Icó" },
  { nome:  "Iguatu" },
  { nome:  "Independência" },
  { nome:  "Ipaporanga" },
  { nome:  "Ipaumirim" },
  { nome:  "Ipu" },
  { nome:  "Ipueiras" },
  { nome:  "Iracema" },
  { nome:  "Irauçuba" },
  { nome:  "Itaiçaba" },
  { nome:  "Itaitinga" },
  { nome:  "Itapajé" },
  { nome:  "Itapipoca" },
  { nome:  "Itapiúna" },
  { nome:  "Itarema" },
  { nome:  "Itatira" },
  { nome:  "Jaguaretama" },
  { nome:  "Jaguaribara" },
  { nome:  "Jaguaribe" },
  { nome:  "Jaguaruana" },
  { nome:  "Jardim" },
  { nome:  "Jati" },
  { nome:  "Jijoca de Jericoaroara" },
  { nome:  "Juazeiro do Norte" },
  { nome:  "Jucás" },
  { nome:  "Lavras da Mangabeira" },
  { nome:  "Limoeiro do Norte" },
  { nome:  "Madalena" },
  { nome:  "Maracanaú" },
  { nome:  "Maranguape" },
  { nome:  "Marco" },
  { nome:  "Martinópole" },
  { nome:  "Massapê" },
  { nome:  "Mauriti" },
  { nome:  "Meruoca" },
  { nome:  "Milagres" },
  { nome:  "Milhã" },
  { nome:  "Miraíma" },
  { nome:  "Missão Velha" },
  { nome:  "Mombaça" },
  { nome:  "Monsenhor Tabosa" },
  { nome:  "Morada Nova" },
  { nome:  "Moraújo" },
  { nome:  "Morrinhos" },
  { nome:  "Mucambo" },
  { nome:  "Mulungu" },
  { nome:  "Nova Olinda" },
  { nome:  "Nova Russas" },
  { nome:  "Novo Oriente" },
  { nome:  "Ocara" },
  { nome:  "Orós" },
  { nome:  "Pacajus" },
  { nome:  "Pacatuba" },
  { nome:  "Pacoti" },
  { nome:  "Pacujá" },
  { nome:  "Palhano" },
  { nome:  "Palmácia" },
  { nome:  "Paracuru" },
  { nome:  "Paraipaba" },
  { nome:  "Parambu" },
  { nome:  "Paramoti" },
  { nome:  "Pedra Branca" },
  { nome:  "Penaforte" },
  { nome:  "Pentecoste" },
  { nome:  "Pereiro" },
  { nome:  "Pindoretama" },
  { nome:  "Piquet Carneiro" },
  { nome:  "Pires Ferreira" },
  { nome:  "Poranga" },
  { nome:  "Porteiras" },
  { nome:  "Potengi" },
  { nome:  "Potiretama" },
  { nome:  "Quiterianópolis" },
  { nome:  "Quixadá" },
  { nome:  "Quixelô" },
  { nome:  "Quixeramobim" },
  { nome:  "Quixeré" },
  { nome:  "Redenção" },
  { nome:  "Reriutaba" },
  { nome:  "Russas" },
  { nome:  "Saboeiro" },
  { nome:  "Salitre" },
  { nome:  "Santa Quitéria" },
  { nome:  "Santana do Acaraú" },
  { nome:  "Santana do Cariri" },
  { nome:  "São Benedito" },
  { nome:  "São Gonçalo do Amarante" },
  { nome:  "São João do Jaguaribe" },
  { nome:  "São Luís do Curu" },
  { nome:  "Senador Pompeu" },
  { nome:  "Senador Sá" },
  { nome:  "Sobral" },
  { nome:  "Solonópole" },
  { nome:  "Tabuleiro do Norte" },
  { nome:  "Tamboril" },
  { nome:  "Tarrafas" },
  { nome:  "Tauá" },
  { nome:  "Tejuçuoca" },
  { nome:  "Tianguá" },
  { nome:  "Trairi" },
  { nome:  "Tururu" },
  { nome:  "Ubajara" },
  { nome:  "Umari" },
  { nome:  "Umirim" },
  { nome:  "Uruburetama" },
  { nome:  "Uruoca" },
  { nome:  "Varjota" },
  { nome:  "Várzea Alegre" },
  { nome:  "Viçosa do Ceará" }
  ]
)