DF = Estado.find_by_sigla("DF")
DF.cidades.create(
  [
  { nome:  "Águas Claras" },
  { nome:  "Arniqueira" },
  { nome:  "Brasília" },
  { nome:  "Brazlândia" },
  { nome:  "Candangolândia" },
  { nome:  "Ceilândia" },
  { nome:  "Cruzeiro" },
  { nome:  "Estrutural" },
  { nome:  "Fercal" },
  { nome:  "Gama" },
  { nome:  "Guará" },
  { nome:  "Itapoã" },
  { nome:  "Jardim Botânico" },
  { nome:  "Lago Norte" },
  { nome:  "Lago Sul" },
  { nome:  "Núcleo Bandeirante" },
  { nome:  "Octogonal" },
  { nome:  "Paranoá" },
  { nome:  "Park Way" },
  { nome:  "Planaltina" },
  { nome:  "Plano Piloto" },
  { nome:  "Pôr do Sol" },
  { nome:  "Recanto das Emas" },
  { nome:  "Riacho Fundo II" },
  { nome:  "Riacho Fundo" },
  { nome:  "Samambaia" },
  { nome:  "Santa Maria" },
  { nome:  "São Sebastião" },
  { nome:  "SIA" },
  { nome:  "Sobradinho II" },
  { nome:  "Sobradinho" },
  { nome:  "Sol Nascente" },
  { nome:  "Sudoeste" },
  { nome:  "Taguatinga" },
  { nome:  "Varjão" },
  { nome:  "Vicente Pires" }
  ]
)