ES = Estado.find_by_sigla("ES")
ES.cidades.create(
  [
  { nome:  "Afonso Cláudio" },
  { nome:  "Água Doce do Norte" },
  { nome:  "Águia Branca" },
  { nome:  "Alegre" },
  { nome:  "Alfredo Chaves" },
  { nome:  "Alto Rio Novo" },
  { nome:  "Anchieta" },
  { nome:  "Apiacá" },
  { nome:  "Aracruz" },
  { nome:  "Atilio Vivacqua" },
  { nome:  "Baixo Guandu" },
  { nome:  "Barra de São Francisco" },
  { nome:  "Boa Esperança" },
  { nome:  "Bom Jesus do Norte" },
  { nome:  "Brejetuba" },
  { nome:  "Cachoeiro de Itapemirim" },
  { nome:  "Cariacica" },
  { nome:  "Castelo" },
  { nome:  "Colatina" },
  { nome:  "Conceição da Barra" },
  { nome:  "Conceição do Castelo" },
  { nome:  "Divino de São Lourenço" },
  { nome:  "Domingos Martins" },
  { nome:  "Dores do Rio Preto" },
  { nome:  "Ecoporanga" },
  { nome:  "Fundão" },
  { nome:  "Governador Lindenberg" },
  { nome:  "Guaçuí" },
  { nome:  "Guarapari" },
  { nome:  "Ibatiba" },
  { nome:  "Ibiraçu" },
  { nome:  "Ibitirama" },
  { nome:  "Iconha" },
  { nome:  "Irupi" },
  { nome:  "Itaguaçu" },
  { nome:  "Itapemirim" },
  { nome:  "Itarana" },
  { nome:  "Iúna" },
  { nome:  "Jaguaré" },
  { nome:  "Jerônimo Monteiro" },
  { nome:  "João Neiva" },
  { nome:  "Laranja da Terra" },
  { nome:  "Linhares" },
  { nome:  "Mantenópolis" },
  { nome:  "Marataizes" },
  { nome:  "Marechal Floriano" },
  { nome:  "Marilândia" },
  { nome:  "Mimoso do Sul" },
  { nome:  "Montanha" },
  { nome:  "Mucurici" },
  { nome:  "Muniz Freire" },
  { nome:  "Muqui" },
  { nome:  "Nova Venécia" },
  { nome:  "Pancas" },
  { nome:  "Pedro Canário" },
  { nome:  "Pinheiros" },
  { nome:  "Piúma" },
  { nome:  "Ponto Belo" },
  { nome:  "Presidente Kennedy" },
  { nome:  "Rio Bananal" },
  { nome:  "Rio Novo do Sul" },
  { nome:  "Santa Leopoldina" },
  { nome:  "Santa Maria de Jetibá" },
  { nome:  "Santa Teresa" },
  { nome:  "São Domingos do Norte" },
  { nome:  "São Gabriel da Palha" },
  { nome:  "São José do Calçado" },
  { nome:  "São Mateus" },
  { nome:  "São Roque do Canaã" },
  { nome:  "Serra" },
  { nome:  "Sooretama" },
  { nome:  "Vargem Alta" },
  { nome:  "Venda Nova do Imigrante" },
  { nome:  "Viana" },
  { nome:  "Vila Pavão" },
  { nome:  "Vila Valério" },
  { nome:  "Vila Velha" },
  { nome:  "Vitória" }
  ]
)