GO = Estado.find_by_sigla("GO")
GO.cidades.create(
  [
  { nome:  "Abadia de Goiás" },
  { nome:  "Abadiânia" },
  { nome:  "Acreúna" },
  { nome:  "Adelândia" },
  { nome:  "Água Fria de Goiás" },
  { nome:  "Água Limpa" },
  { nome:  "Águas Lindas de Goiás" },
  { nome:  "Alexânia" },
  { nome:  "Aloândia" },
  { nome:  "Alto Horizonte" },
  { nome:  "Alto Paraíso de Goiás" },
  { nome:  "Alvorada do Norte" },
  { nome:  "Amaralina" },
  { nome:  "Americano do Brasil" },
  { nome:  "Amorinópolis" },
  { nome:  "Anápolis" },
  { nome:  "Anhanguera" },
  { nome:  "Anicuns" },
  { nome:  "Aparecida de Goiânia" },
  { nome:  "Aparecida do Rio Doce" },
  { nome:  "Aporé" },
  { nome:  "Araçu" },
  { nome:  "Aragarças" },
  { nome:  "Aragoiânia" },
  { nome:  "Araguapaz" },
  { nome:  "Arenópolis" },
  { nome:  "Aruanã" },
  { nome:  "Aurilândia" },
  { nome:  "Avelinópolis" },
  { nome:  "Baliza" },
  { nome:  "Barro Alto" },
  { nome:  "Bela Vista de Goiás" },
  { nome:  "Bom Jardim de Goiás" },
  { nome:  "Bom Jesus de Goiás" },
  { nome:  "Bonfinópolis" },
  { nome:  "Bonópolis" },
  { nome:  "Brazabrantes" },
  { nome:  "Britânia" },
  { nome:  "Buriti Alegre" },
  { nome:  "Buriti de Goiás" },
  { nome:  "Buritinópolis" },
  { nome:  "Cabeceiras" },
  { nome:  "Cachoeira Alta" },
  { nome:  "Cachoeira de Goiás" },
  { nome:  "Cachoeira Dourada" },
  { nome:  "Caçu" },
  { nome:  "Caiapônia" },
  { nome:  "Caldas Novas" },
  { nome:  "Caldazinha" },
  { nome:  "Campestre de Goiás" },
  { nome:  "Campinaçu" },
  { nome:  "Campinorte" },
  { nome:  "Campo Alegre de Goiás" },
  { nome:  "Campos Limpo de Goiás" },
  { nome:  "Campos Belos" },
  { nome:  "Campos Verdes" },
  { nome:  "Carmo do Rio Verde" },
  { nome:  "Castelândia" },
  { nome:  "Catalão" },
  { nome:  "Caturaí" },
  { nome:  "Cavalcante" },
  { nome:  "Ceres" },
  { nome:  "Cezarina" },
  { nome:  "Chapadão do Céu" },
  { nome:  "Cidade Ocidental" },
  { nome:  "Cocalzinho de Goiás" },
  { nome:  "Colinas do Sul" },
  { nome:  "Córrego do Ouro" },
  { nome:  "Corumbá de Goiás" },
  { nome:  "Corumbaíba" },
  { nome:  "Cristalina" },
  { nome:  "Cristianópolis" },
  { nome:  "Crixás" },
  { nome:  "Cromínia" },
  { nome:  "Cumari" },
  { nome:  "Damianópolis" },
  { nome:  "Damolândia" },
  { nome:  "Davinópolis" },
  { nome:  "Diorama" },
  { nome:  "Divinópolis de Goiás" },
  { nome:  "Doverlândia" },
  { nome:  "Edealina" },
  { nome:  "Edéia" },
  { nome:  "Estrela do Norte" },
  { nome:  "Faina" },
  { nome:  "Fazenda Nova" },
  { nome:  "Firminópolis" },
  { nome:  "Flores de Goiás" },
  { nome:  "Formosa" },
  { nome:  "Formoso" },
  { nome:  "Gameleira de Goiás" },
  { nome:  "Goianápolis" },
  { nome:  "Goiandira" },
  { nome:  "Goianésia" },
  { nome:  "Goiânia" },
  { nome:  "Goianira" },
  { nome:  "Goiás" },
  { nome:  "Goiatuba" },
  { nome:  "Gouvelândia" },
  { nome:  "Guapó" },
  { nome:  "Guaraíta" },
  { nome:  "Guarani de Goiás" },
  { nome:  "Guarinos" },
  { nome:  "Heitoraí" },
  { nome:  "Hidrolândia" },
  { nome:  "Hidrolina" },
  { nome:  "Iaciara" },
  { nome:  "Inaciolândia" },
  { nome:  "Indiara" },
  { nome:  "Inhumas" },
  { nome:  "Ipameri" },
  { nome:  "Ipiranga de Goiás" },
  { nome:  "Iporá" },
  { nome:  "Israelândia" },
  { nome:  "Itaberaí" },
  { nome:  "Itaguari" },
  { nome:  "Itaguaru" },
  { nome:  "Itajá" },
  { nome:  "Itapaci" },
  { nome:  "Itapirapuã" },
  { nome:  "Itapuranga" },
  { nome:  "Itarumã" },
  { nome:  "Itauçu" },
  { nome:  "Itumbiara" },
  { nome:  "Ivolândia" },
  { nome:  "Jandaia" },
  { nome:  "Jaraguá" },
  { nome:  "Jataí" },
  { nome:  "Jaupaci" },
  { nome:  "Jesúpolis" },
  { nome:  "Joviânia" },
  { nome:  "Jussara" },
  { nome:  "Lagoa Santa" },
  { nome:  "Leopoldo de Bulhões" },
  { nome:  "Luziânia" },
  { nome:  "Mairipotaba" },
  { nome:  "Mambaí" },
  { nome:  "Mara Rosa" },
  { nome:  "Marzagão" },
  { nome:  "Matrinchã" },
  { nome:  "Maurilândia" },
  { nome:  "Mimoso de Goiás" },
  { nome:  "Minaçu" },
  { nome:  "Mineiros" },
  { nome:  "Moiporá" },
  { nome:  "Monte Alegre de Goiás" },
  { nome:  "Montes Claros de Goiás" },
  { nome:  "Montividiu" },
  { nome:  "Montividiu do Norte" },
  { nome:  "Morrinhos" },
  { nome:  "Morro Agudo de Goiás" },
  { nome:  "Mossâmedes" },
  { nome:  "Mozarlândia" },
  { nome:  "Mundo Novo" },
  { nome:  "Mutunópolis" },
  { nome:  "Nazário" },
  { nome:  "Nerópolis" },
  { nome:  "Niquelândia" },
  { nome:  "Nova América" },
  { nome:  "Nova Aurora" },
  { nome:  "Nova Crixás" },
  { nome:  "Nova Glória" },
  { nome:  "Nova Iguaçu de Goiás" },
  { nome:  "Nova Roma" },
  { nome:  "Nova Veneza" },
  { nome:  "Novo Brasil" },
  { nome:  "Novo Gama" },
  { nome:  "Novo Planalto" },
  { nome:  "Orizona" },
  { nome:  "Ouro Verde de Goiás" },
  { nome:  "Ouvidor" },
  { nome:  "Padre Bernardo" },
  { nome:  "Palestina de Goiás" },
  { nome:  "Palmeiras de Goiás" },
  { nome:  "Palmelo" },
  { nome:  "Palminópolis" },
  { nome:  "Panamá" },
  { nome:  "Paranaiguara" },
  { nome:  "Paraúna" },
  { nome:  "Perolândia" },
  { nome:  "Petrolina de Goiás" },
  { nome:  "Pilar de Goiás" },
  { nome:  "Piracanjuba" },
  { nome:  "Piranhas" },
  { nome:  "Pirenópolis" },
  { nome:  "Pires do Rio" },
  { nome:  "Planaltina" },
  { nome:  "Pontalina" },
  { nome:  "Porangatu" },
  { nome:  "Porteirão" },
  { nome:  "Portelândia" },
  { nome:  "Posse" },
  { nome:  "Professor Jamil" },
  { nome:  "Quirinópolis" },
  { nome:  "Rialma" },
  { nome:  "Rianápolis" },
  { nome:  "Rio Quente" },
  { nome:  "Rio Verde" },
  { nome:  "Rubiataba" },
  { nome:  "Sanclerlândia" },
  { nome:  "Santa Bárbara de Goiás" },
  { nome:  "Santa Cruz de Goiás" },
  { nome:  "Santa Fé de Goiás" },
  { nome:  "Santa Helena de Goiás" },
  { nome:  "Santa Isabel" },
  { nome:  "Santa Rita do Araguaia" },
  { nome:  "Santa Rita do Novo Destino" },
  { nome:  "Santa Rosa de Goiás" },
  { nome:  "Santa Tereza de Goiás" },
  { nome:  "Santa Terezinha de Goiás" },
  { nome:  "Santo Antônio da Barra" },
  { nome:  "Santo Antônio de Goiás" },
  { nome:  "Santo Antônio do Descoberto" },
  { nome:  "São Domingos" },
  { nome:  "São Francisco de Goiás" },
  { nome:  "São João d'Aliança" },
  { nome:  "São João da Paraúna" },
  { nome:  "São Luís de Montes Belos" },
  { nome:  "São Luíz do Norte" },
  { nome:  "São Miguel do Araguaia" },
  { nome:  "São Miguel do Passa Quatro" },
  { nome:  "São Patrício" },
  { nome:  "São Simão" },
  { nome:  "Senador Canedo" },
  { nome:  "Serranópolis" },
  { nome:  "Silvânia" },
  { nome:  "Simolândia" },
  { nome:  "Sítio d'Abadia" },
  { nome:  "Taquaral de Goiás" },
  { nome:  "Teresina de Goiás" },
  { nome:  "Terezópolis de Goiás" },
  { nome:  "Três Ranchos" },
  { nome:  "Trindade" },
  { nome:  "Trombas" },
  { nome:  "Turvânia" },
  { nome:  "Turvelândia" },
  { nome:  "Uirapuru" },
  { nome:  "Uruaçu" },
  { nome:  "Uruana" },
  { nome:  "Urutaí" },
  { nome:  "Valparaíso de Goiás" },
  { nome:  "Varjão" },
  { nome:  "Vianópolis" },
  { nome:  "Vicentinópolis" },
  { nome:  "Vila Boa" },
  { nome:  "Vila Propício" }
  ]
)