MA = Estado.find_by_sigla("MA")
MA.cidades.create(
  [
  { nome: "Açailândia" },
  { nome: "Afonso Cunha" },
  { nome: "Água Doce do Maranhão" },
  { nome: "Alcântara" },
  { nome: "Aldeias Altas" },
  { nome: "Altamira do Maranhão" },
  { nome: "Alto Alegre do Maranhão" },
  { nome: "Alto Alegre do Pindaré" },
  { nome: "Alto Parnaíba" },
  { nome: "Amapá do Maranhão" },
  { nome: "Amarante do Maranhão" },
  { nome: "Anajatuba" },
  { nome: "Anapurus" },
  { nome: "Apicum-Açu" },
  { nome: "Araguanã" },
  { nome: "Araioses" },
  { nome: "Arame" },
  { nome: "Arari" },
  { nome: "Axixá" },
  { nome: "Bacabal" },
  { nome: "Bacabeira" },
  { nome: "Bacuri" },
  { nome: "Bacurituba" },
  { nome: "Balsas" },
  { nome: "Barão de Grajaú" },
  { nome: "Barra do Corda" },
  { nome: "Barreirinhas" },
  { nome: "Bela Vista do Maranhão" },
  { nome: "Belágua" },
  { nome: "Benedito Leite" },
  { nome: "Bequimão" },
  { nome: "Bernardo do Mearim" },
  { nome: "Boa Vista do Gurupi" },
  { nome: "Bom Jardim" },
  { nome: "Bom Jesus das Selvas" },
  { nome: "Bom Lugar" },
  { nome: "Brejo" },
  { nome: "Brejo de Areia" },
  { nome: "Buriti" },
  { nome: "Buriti Bravo" },
  { nome: "Buriticupu" },
  { nome: "Buritirana" },
  { nome: "Cachoeira Grande" },
  { nome: "Cajapió" },
  { nome: "Cajari" },
  { nome: "Campestre do Maranhão" },
  { nome: "Cândido Mendes" },
  { nome: "Cantanhede" },
  { nome: "Capinzal do Norte" },
  { nome: "Carolina" },
  { nome: "Carutapera" },
  { nome: "Caxias" },
  { nome: "Cedral" },
  { nome: "Central do Maranhão" },
  { nome: "Centro do Guilherme" },
  { nome: "Centro Novo do Maranhão" },
  { nome: "Chapadinha" },
  { nome: "Cidelândia" },
  { nome: "Codó" },
  { nome: "Coelho Neto" },
  { nome: "Colinas" },
  { nome: "Conceição do Lago-Açu" },
  { nome: "Coroatá" },
  { nome: "Cururupu" },
  { nome: "Davinópolis" },
  { nome: "Dom Pedro" },
  { nome: "Duque Bacelar" },
  { nome: "Esperantinópolis" },
  { nome: "Estreito" },
  { nome: "Feira Nova do Maranhão" },
  { nome: "Fernando Falcão" },
  { nome: "Formosa da Serra Negra" },
  { nome: "Fortaleza dos Nogueiras" },
  { nome: "Fortuna" },
  { nome: "Godofredo Viana" },
  { nome: "Gonçalves Dias" },
  { nome: "Governador Archer" },
  { nome: "Governador Edison Lobão" },
  { nome: "Governador Eugênio Barros" },
  { nome: "Governador Luiz Rocha" },
  { nome: "Governador Newton Bello" },
  { nome: "Governador Nunes Freire" },
  { nome: "Graça Aranha" },
  { nome: "Grajaú" },
  { nome: "Guimarães" },
  { nome: "Humberto de Campos" },
  { nome: "Icatu" },
  { nome: "Igarapé do Meio" },
  { nome: "Igarapé Grande" },
  { nome: "Imperatriz" },
  { nome: "Itaipava do Grajaú" },
  { nome: "Itapecuru Mirim" },
  { nome: "Itinga do Maranhão" },
  { nome: "Jatobá" },
  { nome: "Jenipapo dos Vieiras" },
  { nome: "João Lisboa" },
  { nome: "Joselândia" },
  { nome: "Junco do Maranhão" },
  { nome: "Lago da Pedra" },
  { nome: "Lago do Junco" },
  { nome: "Lago dos Rodrigues" },
  { nome: "Lago Verde" },
  { nome: "Lagoa do Mato" },
  { nome: "Lagoa Grande do Maranhão" },
  { nome: "Lajeado Novo" },
  { nome: "Lima Campos" },
  { nome: "Loreto" },
  { nome: "Luís Domingues" },
  { nome: "Magalhães de Almeida" },
  { nome: "Maracaçumé" },
  { nome: "Marajá do Sena" },
  { nome: "Maranhãozinho" },
  { nome: "Mata Roma" },
  { nome: "Matinha" },
  { nome: "Matões" },
  { nome: "Matões do Norte" },
  { nome: "Milagres do Maranhão" },
  { nome: "Mirador" },
  { nome: "Miranda do Norte" },
  { nome: "Mirinzal" },
  { nome: "Monção" },
  { nome: "Montes Altos" },
  { nome: "Morros" },
  { nome: "Nina Rodrigues" },
  { nome: "Nova Colinas" },
  { nome: "Nova Iorque" },
  { nome: "Nova Olinda do Maranhão" },
  { nome: "Olho d'Água das Cunhãs" },
  { nome: "Olinda Nova do Maranhão" },
  { nome: "Paço do Lumiar" },
  { nome: "Palmeirândia" },
  { nome: "Paraibano" },
  { nome: "Parnarama" },
  { nome: "Passagem Franca" },
  { nome: "Pastos Bons" },
  { nome: "Paulino Neves" },
  { nome: "Paulo Ramos" },
  { nome: "Pedreiras" },
  { nome: "Pedro do Rosário" },
  { nome: "Penalva" },
  { nome: "Peri Mirim" },
  { nome: "Peritoró" },
  { nome: "Pindaré Mirim" },
  { nome: "Pinheiro" },
  { nome: "Pio XII" },
  { nome: "Pirapemas" },
  { nome: "Poção de Pedras" },
  { nome: "Porto Franco" },
  { nome: "Porto Rico do Maranhão" },
  { nome: "Presidente Dutra" },
  { nome: "Presidente Juscelino" },
  { nome: "Presidente Médici" },
  { nome: "Presidente Sarney" },
  { nome: "Presidente Vargas" },
  { nome: "Primeira Cruz" },
  { nome: "Raposa" },
  { nome: "Riachão" },
  { nome: "Ribamar Fiquene" },
  { nome: "Rosário" },
  { nome: "Sambaíba" },
  { nome: "Santa Filomena do Maranhão" },
  { nome: "Santa Helena" },
  { nome: "Santa Inês" },
  { nome: "Santa Luzia" },
  { nome: "Santa Luzia do Paruá" },
  { nome: "Santa Quitéria do Maranhão" },
  { nome: "Santa Rita" },
  { nome: "Santana do Maranhão" },
  { nome: "Santo Amaro do Maranhão" },
  { nome: "Santo Antônio dos Lopes" },
  { nome: "São Benedito do Rio Preto" },
  { nome: "São Bento" },
  { nome: "São Bernardo" },
  { nome: "São Domingos do Azeitão" },
  { nome: "São Domingos do Maranhão" },
  { nome: "São Félix de Balsas" },
  { nome: "São Francisco do Brejão" },
  { nome: "São Francisco do Maranhão" },
  { nome: "São João Batista" },
  { nome: "São João do Carú" },
  { nome: "São João do Paraíso" },
  { nome: "São João do Soter" },
  { nome: "São João dos Patos" },
  { nome: "São José de Ribamar" },
  { nome: "São José dos Basílios" },
  { nome: "São Luís" },
  { nome: "São Luís Gonzaga do Maranhão" },
  { nome: "São Mateus do Maranhão" },
  { nome: "São Pedro da Água Branca" },
  { nome: "São Pedro dos Crentes" },
  { nome: "São Raimundo das Mangabeiras" },
  { nome: "São Raimundo do Doca Bezerra" },
  { nome: "São Roberto" },
  { nome: "São Vicente Ferrer" },
  { nome: "Satubinha" },
  { nome: "Senador Alexandre Costa" },
  { nome: "Senador La Rocque" },
  { nome: "Serrano do Maranhão" },
  { nome: "Sítio Novo" },
  { nome: "Sucupira do Norte" },
  { nome: "Sucupira do Riachão" },
  { nome: "Tasso Fragoso" },
  { nome: "Timbiras" },
  { nome: "Timon" },
  { nome: "Trizidela do Vale" },
  { nome: "Tufilândia" },
  { nome: "Tuntum" },
  { nome: "Turiaçu" },
  { nome: "Turilândia" },
  { nome: "Tutóia" },
  { nome: "Urbano Santos" },
  { nome: "Vargem Grande" },
  { nome: "Viana" },
  { nome: "Vila Nova dos Martírios" },
  { nome: "Vitória do Mearim" },
  { nome: "Vitorino Freire" },
  { nome: "Zé Doca" }
  ]
)