MG = Estado.find_by_sigla("MG")
MG.cidades.create(
  [
  { nome: "Abadia dos Dourados" },
  { nome: "Abaeté" },
  { nome: "Abre Campo" },
  { nome: "Acaiaca" },
  { nome: "Açucena" },
  { nome: "Água Boa" },
  { nome: "Água Comprida" },
  { nome: "Aguanil" },
  { nome: "Águas Formosas" },
  { nome: "Águas Vermelhas" },
  { nome: "Aimorés" },
  { nome: "Aiuruoca" },
  { nome: "Alagoa" },
  { nome: "Albertina" },
  { nome: "Além Paraíba" },
  { nome: "Alfenas" },
  { nome: "Alfredo Vasconcelos" },
  { nome: "Almenara" },
  { nome: "Alpercata" },
  { nome: "Alpinópolis" },
  { nome: "Alterosa" },
  { nome: "Alto Caparaó" },
  { nome: "Alto Jequitibá" },
  { nome: "Alto Rio Doce" },
  { nome: "Alvarenga" },
  { nome: "Alvinópolis" },
  { nome: "Alvorada de Minas" },
  { nome: "Amparo do Serra" },
  { nome: "Andradas" },
  { nome: "Andrelândia" },
  { nome: "Angelândia" },
  { nome: "Antônio Carlos" },
  { nome: "Antônio Dias" },
  { nome: "Antônio Prado de Minas" },
  { nome: "Araçaí" },
  { nome: "Aracitaba" },
  { nome: "Araçuaí" },
  { nome: "Araguari" },
  { nome: "Arantina" },
  { nome: "Araponga" },
  { nome: "Araporã" },
  { nome: "Arapuá" },
  { nome: "Araújos" },
  { nome: "Araxá" },
  { nome: "Arceburgo" },
  { nome: "Arcos" },
  { nome: "Areado" },
  { nome: "Argirita" },
  { nome: "Aricanduva" },
  { nome: "Arinos" },
  { nome: "Astolfo Dutra" },
  { nome: "Ataléia" },
  { nome: "Augusto de Lima" },
  { nome: "Baependi" },
  { nome: "Baldim" },
  { nome: "Bambuí" },
  { nome: "Bandeira" },
  { nome: "Bandeira do Sul" },
  { nome: "Barão de Cocais" },
  { nome: "Barão de Monte Alto" },
  { nome: "Barbacena" },
  { nome: "Barra Longa" },
  { nome: "Barroso" },
  { nome: "Bela Vista de Minas" },
  { nome: "Belmiro Braga" },
  { nome: "Belo Horizonte" },
  { nome: "Belo Oriente" },
  { nome: "Belo Vale" },
  { nome: "Berilo" },
  { nome: "Berizal" },
  { nome: "Bertópolis" },
  { nome: "Betim" },
  { nome: "Bias Fortes" },
  { nome: "Bicas" },
  { nome: "Biquinhas" },
  { nome: "Boa Esperança" },
  { nome: "Bocaina de Minas" },
  { nome: "Bocaiúva" },
  { nome: "Bom Despacho" },
  { nome: "Bom Jardim de Minas" },
  { nome: "Bom Jesus da Penha" },
  { nome: "Bom Jesus do Amparo" },
  { nome: "Bom Jesus do Galho" },
  { nome: "Bom Repouso" },
  { nome: "Bom Sucesso" },
  { nome: "Bonfim" },
  { nome: "Bonfinópolis de Minas" },
  { nome: "Bonito de Minas" },
  { nome: "Borda da Mata" },
  { nome: "Botelhos" },
  { nome: "Botumirim" },
  { nome: "Brás Pires" },
  { nome: "Brasilândia de Minas" },
  { nome: "Brasília de Minas" },
  { nome: "Brasópolis" },
  { nome: "Braúnas" },
  { nome: "Brumadinho" },
  { nome: "Bueno Brandão" },
  { nome: "Buenópolis" },
  { nome: "Bugre" },
  { nome: "Buritis" },
  { nome: "Buritizeiro" },
  { nome: "Cabeceira Grande" },
  { nome: "Cabo Verde" },
  { nome: "Cachoeira da Prata" },
  { nome: "Cachoeira de Minas" },
  { nome: "Cachoeira de Pajeú" },
  { nome: "Cachoeira Dourada" },
  { nome: "Caetanópolis" },
  { nome: "Caeté" },
  { nome: "Caiana" },
  { nome: "Cajuri" },
  { nome: "Caldas" },
  { nome: "Camacho" },
  { nome: "Camanducaia" },
  { nome: "Cambuí" },
  { nome: "Cambuquira" },
  { nome: "Campanário" },
  { nome: "Campanha" },
  { nome: "Campestre" },
  { nome: "Campina Verde" },
  { nome: "Campo Azul" },
  { nome: "Campo Belo" },
  { nome: "Campo do Meio" },
  { nome: "Campo Florido" },
  { nome: "Campos Altos" },
  { nome: "Campos Gerais" },
  { nome: "Cana Verde" },
  { nome: "Canaã" },
  { nome: "Canápolis" },
  { nome: "Candeias" },
  { nome: "Cantagalo" },
  { nome: "Caparaó" },
  { nome: "Capela Nova" },
  { nome: "Capelinha" },
  { nome: "Capetinga" },
  { nome: "Capim Branco" },
  { nome: "Capinópolis" },
  { nome: "Capitão Andrade" },
  { nome: "Capitão Enéas" },
  { nome: "Capitólio" },
  { nome: "Caputira" },
  { nome: "Caraí" },
  { nome: "Caranaíba" },
  { nome: "Carandaí" },
  { nome: "Carangola" },
  { nome: "Caratinga" },
  { nome: "Carbonita" },
  { nome: "Careaçu" },
  { nome: "Carlos Chagas" },
  { nome: "Carmésia" },
  { nome: "Carmo da Cachoeira" },
  { nome: "Carmo da Mata" },
  { nome: "Carmo de Minas" },
  { nome: "Carmo do Cajuru" },
  { nome: "Carmo do Paranaíba" },
  { nome: "Carmo do Rio Claro" },
  { nome: "Carmópolis de Minas" },
  { nome: "Carneirinho" },
  { nome: "Carrancas" },
  { nome: "Carvalhópolis" },
  { nome: "Carvalhos" },
  { nome: "Casa Grande" },
  { nome: "Cascalho Rico" },
  { nome: "Cássia" },
  { nome: "Cataguases" },
  { nome: "Catas Altas" },
  { nome: "Catas Altas da Noruega" },
  { nome: "Catuji" },
  { nome: "Catuti" },
  { nome: "Caxambu" },
  { nome: "Cedro do Abaeté" },
  { nome: "Central de Minas" },
  { nome: "Centralina" },
  { nome: "Chácara" },
  { nome: "Chalé" },
  { nome: "Chapada do Norte" },
  { nome: "Chapada Gaúcha" },
  { nome: "Chiador" },
  { nome: "Cipotânea" },
  { nome: "Claraval" },
  { nome: "Claro dos Poções" },
  { nome: "Cláudio" },
  { nome: "Coimbra" },
  { nome: "Coluna" },
  { nome: "Comendador Gomes" },
  { nome: "Comercinho" },
  { nome: "Conceição da Aparecida" },
  { nome: "Conceição da Barra de Minas" },
  { nome: "Conceição das Alagoas" },
  { nome: "Conceição das Pedras" },
  { nome: "Conceição de Ipanema" },
  { nome: "Conceição do Mato Dentro" },
  { nome: "Conceição do Pará" },
  { nome: "Conceição do Rio Verde" },
  { nome: "Conceição dos Ouros" },
  { nome: "Cônego Marinho" },
  { nome: "Confins" },
  { nome: "Congonhal" },
  { nome: "Congonhas" },
  { nome: "Congonhas do Norte" },
  { nome: "Conquista" },
  { nome: "Conselheiro Lafaiete" },
  { nome: "Conselheiro Pena" },
  { nome: "Consolação" },
  { nome: "Contagem" },
  { nome: "Coqueiral" },
  { nome: "Coração de Jesus" },
  { nome: "Cordisburgo" },
  { nome: "Cordislândia" },
  { nome: "Corinto" },
  { nome: "Coroaci" },
  { nome: "Coromandel" },
  { nome: "Coronel Fabriciano" },
  { nome: "Coronel Murta" },
  { nome: "Coronel Pacheco" },
  { nome: "Coronel Xavier Chaves" },
  { nome: "Córrego Danta" },
  { nome: "Córrego do Bom Jesus" },
  { nome: "Córrego Fundo" },
  { nome: "Córrego Novo" },
  { nome: "Couto de Magalhães de Minas" },
  { nome: "Crisólita" },
  { nome: "Cristais" },
  { nome: "Cristália" },
  { nome: "Cristiano Otoni" },
  { nome: "Cristina" },
  { nome: "Crucilândia" },
  { nome: "Cruzeiro da Fortaleza" },
  { nome: "Cruzília" },
  { nome: "Cuparaque" },
  { nome: "Curral de Dentro" },
  { nome: "Curvelo" },
  { nome: "Datas" },
  { nome: "Delfim Moreira" },
  { nome: "Delfinópolis" },
  { nome: "Delta" },
  { nome: "Descoberto" },
  { nome: "Desterro de Entre Rios" },
  { nome: "Desterro do Melo" },
  { nome: "Diamantina" },
  { nome: "Diogo de Vasconcelos" },
  { nome: "Dionísio" },
  { nome: "Divinésia" },
  { nome: "Divino" },
  { nome: "Divino das Laranjeiras" },
  { nome: "Divinolândia de Minas" },
  { nome: "Divinópolis" },
  { nome: "Divisa Alegre" },
  { nome: "Divisa Nova" },
  { nome: "Divisópolis" },
  { nome: "Dom Bosco" },
  { nome: "Dom Cavati" },
  { nome: "Dom Joaquim" },
  { nome: "Dom Silvério" },
  { nome: "Dom Viçoso" },
  { nome: "Dona Euzébia" },
  { nome: "Dores de Campos" },
  { nome: "Dores de Guanhães" },
  { nome: "Dores do Indaiá" },
  { nome: "Dores do Turvo" },
  { nome: "Doresópolis" },
  { nome: "Douradoquara" },
  { nome: "Durandé" },
  { nome: "Elói Mendes" },
  { nome: "Engenheiro Caldas" },
  { nome: "Engenheiro Navarro" },
  { nome: "Entre Folhas" },
  { nome: "Entre Rios de Minas" },
  { nome: "Ervália" },
  { nome: "Esmeraldas" },
  { nome: "Espera Feliz" },
  { nome: "Espinosa" },
  { nome: "Espírito Santo do Dourado" },
  { nome: "Estiva" },
  { nome: "Estrela Dalva" },
  { nome: "Estrela do Indaiá" },
  { nome: "Estrela do Sul" },
  { nome: "Eugenópolis" },
  { nome: "Ewbank da Câmara" },
  { nome: "Extrema" },
  { nome: "Fama" },
  { nome: "Faria Lemos" },
  { nome: "Felício dos Santos" },
  { nome: "Felisburgo" },
  { nome: "Felixlândia" },
  { nome: "Fernandes Tourinho" },
  { nome: "Ferros" },
  { nome: "Fervedouro" },
  { nome: "Florestal" },
  { nome: "Formiga" },
  { nome: "Formoso" },
  { nome: "Fortaleza de Minas" },
  { nome: "Fortuna de Minas" },
  { nome: "Francisco Badaró" },
  { nome: "Francisco Dumont" },
  { nome: "Francisco Sá" },
  { nome: "Franciscópolis" },
  { nome: "Frei Gaspar" },
  { nome: "Frei Inocêncio" },
  { nome: "Frei Lagonegro" },
  { nome: "Fronteira" },
  { nome: "Fronteira dos Vales" },
  { nome: "Fruta de Leite" },
  { nome: "Frutal" },
  { nome: "Funilândia" },
  { nome: "Galiléia" },
  { nome: "Gameleiras" },
  { nome: "Glaucilândia" },
  { nome: "Goiabeira" },
  { nome: "Goianá" },
  { nome: "Gonçalves" },
  { nome: "Gonzaga" },
  { nome: "Gouveia" },
  { nome: "Governador Valadares" },
  { nome: "Grão Mogol" },
  { nome: "Grupiara" },
  { nome: "Guanhães" },
  { nome: "Guapé" },
  { nome: "Guaraciaba" },
  { nome: "Guaraciama" },
  { nome: "Guaranésia" },
  { nome: "Guarani" },
  { nome: "Guarará" },
  { nome: "Guarda-Mor" },
  { nome: "Guaxupé" },
  { nome: "Guidoval" },
  { nome: "Guimarânia" },
  { nome: "Guiricema" },
  { nome: "Gurinhatã" },
  { nome: "Heliodora" },
  { nome: "Iapu" },
  { nome: "Ibertioga" },
  { nome: "Ibiá" },
  { nome: "Ibiaí" },
  { nome: "Ibiracatu" },
  { nome: "Ibiraci" },
  { nome: "Ibirité" },
  { nome: "Ibitiúra de Minas" },
  { nome: "Ibituruna" },
  { nome: "Icaraí de Minas" },
  { nome: "Igarapé" },
  { nome: "Igaratinga" },
  { nome: "Iguatama" },
  { nome: "Ijaci" },
  { nome: "Ilicínea" },
  { nome: "Imbé de Minas" },
  { nome: "Inconfidentes" },
  { nome: "Indaiabira" },
  { nome: "Indianópolis" },
  { nome: "Ingaí" },
  { nome: "Inhapim" },
  { nome: "Inhaúma" },
  { nome: "Inimutaba" },
  { nome: "Ipaba" },
  { nome: "Ipanema" },
  { nome: "Ipatinga" },
  { nome: "Ipiaçu" },
  { nome: "Ipuiúna" },
  { nome: "Iraí de Minas" },
  { nome: "Itabira" },
  { nome: "Itabirinha de Mantena" },
  { nome: "Itabirito" },
  { nome: "Itacambira" },
  { nome: "Itacarambi" },
  { nome: "Itaguara" },
  { nome: "Itaipé" },
  { nome: "Itajubá" },
  { nome: "Itamarandiba" },
  { nome: "Itamarati de Minas" },
  { nome: "Itambacuri" },
  { nome: "Itambé do Mato Dentro" },
  { nome: "Itamogi" },
  { nome: "Itamonte" },
  { nome: "Itanhandu" },
  { nome: "Itanhomi" },
  { nome: "Itaobim" },
  { nome: "Itapagipe" },
  { nome: "Itapecerica" },
  { nome: "Itapeva" },
  { nome: "Itatiaiuçu" },
  { nome: "Itaú de Minas" },
  { nome: "Itaúna" },
  { nome: "Itaverava" },
  { nome: "Itinga" },
  { nome: "Itueta" },
  { nome: "Ituiutaba" },
  { nome: "Itumirim" },
  { nome: "Iturama" },
  { nome: "Itutinga" },
  { nome: "Jaboticatubas" },
  { nome: "Jacinto" },
  { nome: "Jacuí" },
  { nome: "Jacutinga" },
  { nome: "Jaguaraçu" },
  { nome: "Jaíba" },
  { nome: "Jampruca" },
  { nome: "Janaúba" },
  { nome: "Januária" },
  { nome: "Japaraíba" },
  { nome: "Japonvar" },
  { nome: "Jeceaba" },
  { nome: "Jenipapo de Minas" },
  { nome: "Jequeri" },
  { nome: "Jequitaí" },
  { nome: "Jequitibá" },
  { nome: "Jequitinhonha" },
  { nome: "Jesuânia" },
  { nome: "Joaíma" },
  { nome: "Joanésia" },
  { nome: "João Monlevade" },
  { nome: "João Pinheiro" },
  { nome: "Joaquim Felício" },
  { nome: "Jordânia" },
  { nome: "José Gonçalves de Minas" },
  { nome: "José Raydan" },
  { nome: "Josenópolis" },
  { nome: "Juatuba" },
  { nome: "Juiz de Fora" },
  { nome: "Juramento" },
  { nome: "Juruaia" },
  { nome: "Juvenília" },
  { nome: "Ladainha" },
  { nome: "Lagamar" },
  { nome: "Lagoa da Prata" },
  { nome: "Lagoa dos Patos" },
  { nome: "Lagoa Dourada" },
  { nome: "Lagoa Formosa" },
  { nome: "Lagoa Grande" },
  { nome: "Lagoa Santa" },
  { nome: "Lajinha" },
  { nome: "Lambari" },
  { nome: "Lamim" },
  { nome: "Laranjal" },
  { nome: "Lassance" },
  { nome: "Lavras" },
  { nome: "Leandro Ferreira" },
  { nome: "Leme do Prado" },
  { nome: "Leopoldina" },
  { nome: "Liberdade" },
  { nome: "Lima Duarte" },
  { nome: "Limeira do Oeste" },
  { nome: "Lontra" },
  { nome: "Luisburgo" },
  { nome: "Luislândia" },
  { nome: "Luminárias" },
  { nome: "Luz" },
  { nome: "Machacalis" },
  { nome: "Machado" },
  { nome: "Madre de Deus de Minas" },
  { nome: "Malacacheta" },
  { nome: "Mamonas" },
  { nome: "Manga" },
  { nome: "Manhuaçu" },
  { nome: "Manhumirim" },
  { nome: "Mantena" },
  { nome: "Mar de Espanha" },
  { nome: "Maravilhas" },
  { nome: "Maria da Fé" },
  { nome: "Mariana" },
  { nome: "Marilac" },
  { nome: "Mário Campos" },
  { nome: "Maripá de Minas" },
  { nome: "Marliéria" },
  { nome: "Marmelópolis" },
  { nome: "Martinho Campos" },
  { nome: "Martins Soares" },
  { nome: "Mata Verde" },
  { nome: "Materlândia" },
  { nome: "Mateus Leme" },
  { nome: "Mathias Lobato" },
  { nome: "Matias Barbosa" },
  { nome: "Matias Cardoso" },
  { nome: "Matipó" },
  { nome: "Mato Verde" },
  { nome: "Matozinhos" },
  { nome: "Matutina" },
  { nome: "Medeiros" },
  { nome: "Medina" },
  { nome: "Mendes Pimentel" },
  { nome: "Mercês" },
  { nome: "Mesquita" },
  { nome: "Minas Novas" },
  { nome: "Minduri" },
  { nome: "Mirabela" },
  { nome: "Miradouro" },
  { nome: "Miraí" },
  { nome: "Miravânia" },
  { nome: "Moeda" },
  { nome: "Moema" },
  { nome: "Monjolos" },
  { nome: "Monsenhor Paulo" },
  { nome: "Montalvânia" },
  { nome: "Monte Alegre de Minas" },
  { nome: "Monte Azul" },
  { nome: "Monte Belo" },
  { nome: "Monte Carmelo" },
  { nome: "Monte Formoso" },
  { nome: "Monte Santo de Minas" },
  { nome: "Monte Sião" },
  { nome: "Montes Claros" },
  { nome: "Montezuma" },
  { nome: "Morada Nova de Minas" },
  { nome: "Morro da Garça" },
  { nome: "Morro do Pilar" },
  { nome: "Munhoz" },
  { nome: "Muriaé" },
  { nome: "Mutum" },
  { nome: "Muzambinho" },
  { nome: "Nacip Raydan" },
  { nome: "Nanuque" },
  { nome: "Naque" },
  { nome: "Natalândia" },
  { nome: "Natércia" },
  { nome: "Nazareno" },
  { nome: "Nepomuceno" },
  { nome: "Ninheira" },
  { nome: "Nova Belém" },
  { nome: "Nova Era" },
  { nome: "Nova Lima" },
  { nome: "Nova Módica" },
  { nome: "Nova Ponte" },
  { nome: "Nova Porteirinha" },
  { nome: "Nova Resende" },
  { nome: "Nova Serrana" },
  { nome: "Nova União" },
  { nome: "Novo Cruzeiro" },
  { nome: "Novo Oriente de Minas" },
  { nome: "Novorizonte" },
  { nome: "Olaria" },
  { nome: "Olhos-d'Água" },
  { nome: "Olímpio Noronha" },
  { nome: "Oliveira" },
  { nome: "Oliveira Fortes" },
  { nome: "Onça de Pitangui" },
  { nome: "Oratórios" },
  { nome: "Orizânia" },
  { nome: "Ouro Branco" },
  { nome: "Ouro Fino" },
  { nome: "Ouro Preto" },
  { nome: "Ouro Verde de Minas" },
  { nome: "Padre Carvalho" },
  { nome: "Padre Paraíso" },
  { nome: "Pai Pedro" },
  { nome: "Paineiras" },
  { nome: "Pains" },
  { nome: "Paiva" },
  { nome: "Palma" },
  { nome: "Palmópolis" },
  { nome: "Papagaios" },
  { nome: "Pará de Minas" },
  { nome: "Paracatu" },
  { nome: "Paraguaçu" },
  { nome: "Paraisópolis" },
  { nome: "Paraopeba" },
  { nome: "Passa Quatro" },
  { nome: "Passa Tempo" },
  { nome: "Passa-Vinte" },
  { nome: "Passabém" },
  { nome: "Passos" },
  { nome: "Patis" },
  { nome: "Patos de Minas" },
  { nome: "Patrocínio" },
  { nome: "Patrocínio do Muriaé" },
  { nome: "Paula Cândido" },
  { nome: "Paulistas" },
  { nome: "Pavão" },
  { nome: "Peçanha" },
  { nome: "Pedra Azul" },
  { nome: "Pedra Bonita" },
  { nome: "Pedra do Anta" },
  { nome: "Pedra do Indaiá" },
  { nome: "Pedra Dourada" },
  { nome: "Pedralva" },
  { nome: "Pedras de Maria da Cruz" },
  { nome: "Pedrinópolis" },
  { nome: "Pedro Leopoldo" },
  { nome: "Pedro Teixeira" },
  { nome: "Pequeri" },
  { nome: "Pequi" },
  { nome: "Perdigão" },
  { nome: "Perdizes" },
  { nome: "Perdões" },
  { nome: "Periquito" },
  { nome: "Pescador" },
  { nome: "Piau" },
  { nome: "Piedade de Caratinga" },
  { nome: "Piedade de Ponte Nova" },
  { nome: "Piedade do Rio Grande" },
  { nome: "Piedade dos Gerais" },
  { nome: "Pimenta" },
  { nome: "Pingo-d'Água" },
  { nome: "Pintópolis" },
  { nome: "Piracema" },
  { nome: "Pirajuba" },
  { nome: "Piranga" },
  { nome: "Piranguçu" },
  { nome: "Piranguinho" },
  { nome: "Pirapetinga" },
  { nome: "Pirapora" },
  { nome: "Piraúba" },
  { nome: "Pitangui" },
  { nome: "Piumhi" },
  { nome: "Planura" },
  { nome: "Poço Fundo" },
  { nome: "Poços de Caldas" },
  { nome: "Pocrane" },
  { nome: "Pompéu" },
  { nome: "Ponte Nova" },
  { nome: "Ponto Chique" },
  { nome: "Ponto dos Volantes" },
  { nome: "Porteirinha" },
  { nome: "Porto Firme" },
  { nome: "Poté" },
  { nome: "Pouso Alegre" },
  { nome: "Pouso Alto" },
  { nome: "Prados" },
  { nome: "Prata" },
  { nome: "Pratápolis" },
  { nome: "Pratinha" },
  { nome: "Presidente Bernardes" },
  { nome: "Presidente Juscelino" },
  { nome: "Presidente Kubitschek" },
  { nome: "Presidente Olegário" },
  { nome: "Prudente de Morais" },
  { nome: "Quartel Geral" },
  { nome: "Queluzito" },
  { nome: "Raposos" },
  { nome: "Raul Soares" },
  { nome: "Recreio" },
  { nome: "Reduto" },
  { nome: "Resende Costa" },
  { nome: "Resplendor" },
  { nome: "Ressaquinha" },
  { nome: "Riachinho" },
  { nome: "Riacho dos Machados" },
  { nome: "Ribeirão das Neves" },
  { nome: "Ribeirão Vermelho" },
  { nome: "Rio Acima" },
  { nome: "Rio Casca" },
  { nome: "Rio do Prado" },
  { nome: "Rio Doce" },
  { nome: "Rio Espera" },
  { nome: "Rio Manso" },
  { nome: "Rio Novo" },
  { nome: "Rio Paranaíba" },
  { nome: "Rio Pardo de Minas" },
  { nome: "Rio Piracicaba" },
  { nome: "Rio Pomba" },
  { nome: "Rio Preto" },
  { nome: "Rio Vermelho" },
  { nome: "Ritápolis" },
  { nome: "Rochedo de Minas" },
  { nome: "Rodeiro" },
  { nome: "Romaria" },
  { nome: "Rosário da Limeira" },
  { nome: "Rubelita" },
  { nome: "Rubim" },
  { nome: "Sabará" },
  { nome: "Sabinópolis" },
  { nome: "Sacramento" },
  { nome: "Salinas" },
  { nome: "Salto da Divisa" },
  { nome: "Santa Bárbara" },
  { nome: "Santa Bárbara do Leste" },
  { nome: "Santa Bárbara do Monte Verde" },
  { nome: "Santa Bárbara do Tugúrio" },
  { nome: "Santa Cruz de Minas" },
  { nome: "Santa Cruz de Salinas" },
  { nome: "Santa Cruz do Escalvado" },
  { nome: "Santa Efigênia de Minas" },
  { nome: "Santa Fé de Minas" },
  { nome: "Santa Helena de Minas" },
  { nome: "Santa Juliana" },
  { nome: "Santa Luzia" },
  { nome: "Santa Margarida" },
  { nome: "Santa Maria de Itabira" },
  { nome: "Santa Maria do Salto" },
  { nome: "Santa Maria do Suaçuí" },
  { nome: "Santa Rita de Caldas" },
  { nome: "Santa Rita de Ibitipoca" },
  { nome: "Santa Rita de Jacutinga" },
  { nome: "Santa Rita de Minas" },
  { nome: "Santa Rita do Itueto" },
  { nome: "Santa Rita do Sapucaí" },
  { nome: "Santa Rosa da Serra" },
  { nome: "Santa Vitória" },
  { nome: "Santana da Vargem" },
  { nome: "Santana de Cataguases" },
  { nome: "Santana de Pirapama" },
  { nome: "Santana do Deserto" },
  { nome: "Santana do Garambéu" },
  { nome: "Santana do Jacaré" },
  { nome: "Santana do Manhuaçu" },
  { nome: "Santana do Paraíso" },
  { nome: "Santana do Riacho" },
  { nome: "Santana dos Montes" },
  { nome: "Santo Antônio do Amparo" },
  { nome: "Santo Antônio do Aventureiro" },
  { nome: "Santo Antônio do Grama" },
  { nome: "Santo Antônio do Itambé" },
  { nome: "Santo Antônio do Jacinto" },
  { nome: "Santo Antônio do Monte" },
  { nome: "Santo Antônio do Retiro" },
  { nome: "Santo Antônio do Rio Abaixo" },
  { nome: "Santo Hipólito" },
  { nome: "Santos Dumont" },
  { nome: "São Bento Abade" },
  { nome: "São Brás do Suaçuí" },
  { nome: "São Domingos das Dores" },
  { nome: "São Domingos do Prata" },
  { nome: "São Félix de Minas" },
  { nome: "São Francisco" },
  { nome: "São Francisco de Paula" },
  { nome: "São Francisco de Sales" },
  { nome: "São Francisco do Glória" },
  { nome: "São Geraldo" },
  { nome: "São Geraldo da Piedade" },
  { nome: "São Geraldo do Baixio" },
  { nome: "São Gonçalo do Abaeté" },
  { nome: "São Gonçalo do Pará" },
  { nome: "São Gonçalo do Rio Abaixo" },
  { nome: "São Gonçalo do Rio Preto" },
  { nome: "São Gonçalo do Sapucaí" },
  { nome: "São Gotardo" },
  { nome: "São João Batista do Glória" },
  { nome: "São João da Lagoa" },
  { nome: "São João da Mata" },
  { nome: "São João da Ponte" },
  { nome: "São João das Missões" },
  { nome: "São João del Rei" },
  { nome: "São João do Manhuaçu" },
  { nome: "São João do Manteninha" },
  { nome: "São João do Oriente" },
  { nome: "São João do Pacuí" },
  { nome: "São João do Paraíso" },
  { nome: "São João Evangelista" },
  { nome: "São João Nepomuceno" },
  { nome: "São Joaquim de Bicas" },
  { nome: "São José da Barra" },
  { nome: "São José da Lapa" },
  { nome: "São José da Safira" },
  { nome: "São José da Varginha" },
  { nome: "São José do Alegre" },
  { nome: "São José do Divino" },
  { nome: "São José do Goiabal" },
  { nome: "São José do Jacuri" },
  { nome: "São José do Mantimento" },
  { nome: "São Lourenço" },
  { nome: "São Miguel do Anta" },
  { nome: "São Pedro da União" },
  { nome: "São Pedro do Suaçuí" },
  { nome: "São Pedro dos Ferros" },
  { nome: "São Romão" },
  { nome: "São Roque de Minas" },
  { nome: "São Sebastião da Bela Vista" },
  { nome: "São Sebastião da Vargem Alegre" },
  { nome: "São Sebastião do Anta" },
  { nome: "São Sebastião do Maranhão" },
  { nome: "São Sebastião do Oeste" },
  { nome: "São Sebastião do Paraíso" },
  { nome: "São Sebastião do Rio Preto" },
  { nome: "São Sebastião do Rio Verde" },
  { nome: "São Thomé das Letras" },
  { nome: "São Tiago" },
  { nome: "São Tomás de Aquino" },
  { nome: "São Vicente de Minas" },
  { nome: "Sapucaí-Mirim" },
  { nome: "Sardoá" },
  { nome: "Sarzedo" },
  { nome: "Sem-Peixe" },
  { nome: "Senador Amaral" },
  { nome: "Senador Cortes" },
  { nome: "Senador Firmino" },
  { nome: "Senador José Bento" },
  { nome: "Senador Modestino Gonçalves" },
  { nome: "Senhora de Oliveira" },
  { nome: "Senhora do Porto" },
  { nome: "Senhora dos Remédios" },
  { nome: "Sericita" },
  { nome: "Seritinga" },
  { nome: "Serra Azul de Minas" },
  { nome: "Serra da Saudade" },
  { nome: "Serra do Salitre" },
  { nome: "Serra dos Aimorés" },
  { nome: "Serrania" },
  { nome: "Serranópolis de Minas" },
  { nome: "Serranos" },
  { nome: "Serro" },
  { nome: "Sete Lagoas" },
  { nome: "Setubinha" },
  { nome: "Silveirânia" },
  { nome: "Silvianópolis" },
  { nome: "Simão Pereira" },
  { nome: "Simonésia" },
  { nome: "Sobrália" },
  { nome: "Soledade de Minas" },
  { nome: "Tabuleiro" },
  { nome: "Taiobeiras" },
  { nome: "Taparuba" },
  { nome: "Tapira" },
  { nome: "Tapiraí" },
  { nome: "Taquaraçu de Minas" },
  { nome: "Tarumirim" },
  { nome: "Teixeiras" },
  { nome: "Teófilo Otoni" },
  { nome: "Timóteo" },
  { nome: "Tiradentes" },
  { nome: "Tiros" },
  { nome: "Tocantins" },
  { nome: "Tocos do Moji" },
  { nome: "Toledo" },
  { nome: "Tombos" },
  { nome: "Três Corações" },
  { nome: "Três Marias" },
  { nome: "Três Pontas" },
  { nome: "Tumiritinga" },
  { nome: "Tupaciguara" },
  { nome: "Turmalina" },
  { nome: "Turvolândia" },
  { nome: "Ubá" },
  { nome: "Ubaí" },
  { nome: "Ubaporanga" },
  { nome: "Uberaba" },
  { nome: "Uberlândia" },
  { nome: "Umburatiba" },
  { nome: "Unaí" },
  { nome: "União de Minas" },
  { nome: "Uruana de Minas" },
  { nome: "Urucânia" },
  { nome: "Urucuia" },
  { nome: "Vargem Alegre" },
  { nome: "Vargem Bonita" },
  { nome: "Vargem Grande do Rio Pardo" },
  { nome: "Varginha" },
  { nome: "Varjão de Minas" },
  { nome: "Várzea da Palma" },
  { nome: "Varzelândia" },
  { nome: "Vazante" },
  { nome: "Verdelândia" },
  { nome: "Veredinha" },
  { nome: "Veríssimo" },
  { nome: "Vermelho Novo" },
  { nome: "Vespasiano" },
  { nome: "Viçosa" },
  { nome: "Vieiras" },
  { nome: "Virgem da Lapa" },
  { nome: "Virgínia" },
  { nome: "Virginópolis" },
  { nome: "Virgolândia" },
  { nome: "Visconde do Rio Branco" },
  { nome: "Volta Grande" },
  { nome: "Wenceslau Braz" }
  ]
)