MS = Estado.find_by_sigla("MS")
MS.cidades.create(
  [
   { nome: "Água Clara" },
   { nome: "Alcinópolis" },
   { nome: "Amambaí" },
   { nome: "Anastácio" },
   { nome: "Anaurilândia" },
   { nome: "Angélica" },
   { nome: "Antônio João" },
   { nome: "Aparecida do Taboado" },
   { nome: "Aquidauana" },
   { nome: "Aral Moreira" },
   { nome: "Bandeirantes" },
   { nome: "Bataguassu" },
   { nome: "Bataiporã" },
   { nome: "Bela Vista" },
   { nome: "Bodoquena" },
   { nome: "Bonito" },
   { nome: "Brasilândia" },
   { nome: "Caarapó" },
   { nome: "Camapuã" },
   { nome: "Campo Grande" },
   { nome: "Caracol" },
   { nome: "Cassilândia" },
   { nome: "Chapadão do Sul" },
   { nome: "Corguinho" },
   { nome: "Coronel Sapucaia" },
   { nome: "Corumbá" },
   { nome: "Costa Rica" },
   { nome: "Coxim" },
   { nome: "Deodápolis" },
   { nome: "Dois Irmãos do Buriti" },
   { nome: "Douradina" },
   { nome: "Dourados" },
   { nome: "Eldorado" },
   { nome: "Fátima do Sul" },
   { nome: "Glória de Dourados" },
   { nome: "Guia Lopes da Laguna" },
   { nome: "Iguatemi" },
   { nome: "Inocência" },
   { nome: "Itaporã" },
   { nome: "Itaquiraí" },
   { nome: "Ivinhema" },
   { nome: "Japorã" },
   { nome: "Jaraguari" },
   { nome: "Jardim" },
   { nome: "Jateí" },
   { nome: "Juti" },
   { nome: "Ladário" },
   { nome: "Laguna Carapã" },
   { nome: "Maracaju" },
   { nome: "Miranda" },
   { nome: "Mundo Novo" },
   { nome: "Naviraí" },
   { nome: "Nioaque" },
   { nome: "Nova Alvorada do Sul" },
   { nome: "Nova Andradina" },
   { nome: "Novo Horizonte do Sul" },
   { nome: "Paranaíba" },
   { nome: "Paranhos" },
   { nome: "Pedro Gomes" },
   { nome: "Ponta Porã" },
   { nome: "Porto Murtinho" },
   { nome: "Ribas do Rio Pardo" },
   { nome: "Rio Brilhante" },
   { nome: "Rio Negro" },
   { nome: "Rio Verde de Mato Grosso" },
   { nome: "Rochedo" },
   { nome: "Santa Rita do Pardo" },
   { nome: "São Gabriel do Oeste" },
   { nome: "Selvíria" },
   { nome: "Sete Quedas" },
   { nome: "Sidrolândia" },
   { nome: "Sonora" },
   { nome: "Tacuru" },
   { nome: "Taquarussu" },
   { nome: "Terenos" },
   { nome: "Três Lagoas" },
   { nome: "Vicentina" }
  ]
)