MT = Estado.find_by_sigla("MT")
MT.cidades.create(
  [
   { nome: "Acorizal" },
   { nome: "Água Boa" },
   { nome: "Alta Floresta" },
   { nome: "Alto Araguaia" },
   { nome: "Alto Boa Vista" },
   { nome: "Alto Garças" },
   { nome: "Alto Paraguai" },
   { nome: "Alto Taquari" },
   { nome: "Apiacás" },
   { nome: "Araguaiana" },
   { nome: "Araguainha" },
   { nome: "Araputanga" },
   { nome: "Arenápolis" },
   { nome: "Aripuanã" },
   { nome: "Barão de Melgaço" },
   { nome: "Barra do Bugres" },
   { nome: "Barra do Garças" },
   { nome: "Bom Jesus do Araguaia" },
   { nome: "Brasnorte" },
   { nome: "Cáceres" },
   { nome: "Campinápolis" },
   { nome: "Campo Novo do Parecis" },
   { nome: "Campo Verde" },
   { nome: "Campos de Júlio" },
   { nome: "Canabrava do Norte" },
   { nome: "Canarana" },
   { nome: "Carlinda" },
   { nome: "Castanheira" },
   { nome: "Chapada dos Guimarães" },
   { nome: "Cláudia" },
   { nome: "Cocalinho" },
   { nome: "Colíder" },
   { nome: "Colniza" },
   { nome: "Comodoro" },
   { nome: "Confresa" },
   { nome: "Conquista d'Oeste" },
   { nome: "Cotriguaçu" },
   { nome: "Curvelândia" },
   { nome: "Cuiabá" },
   { nome: "Denise" },
   { nome: "Diamantino" },
   { nome: "Dom Aquino" },
   { nome: "Feliz Natal" },
   { nome: "Figueirópolis d'Oeste" },
   { nome: "Gaúcha do Norte" },
   { nome: "General Carneiro" },
   { nome: "Glória d'Oeste" },
   { nome: "Guarantã do Norte" },
   { nome: "Guiratinga" },
   { nome: "Indiavaí" },
   { nome: "Itaúba" },
   { nome: "Itiquira" },
   { nome: "Jaciara" },
   { nome: "Jangada" },
   { nome: "Jauru" },
   { nome: "Juara" },
   { nome: "Juína" },
   { nome: "Juruena" },
   { nome: "Juscimeira" },
   { nome: "Lambari d'Oeste" },
   { nome: "Lucas do Rio Verde" },
   { nome: "Luciára" },
   { nome: "Marcelândia" },
   { nome: "Matupá" },
   { nome: "Mirassol d'Oeste" },
   { nome: "Nobres" },
   { nome: "Nortelândia" },
   { nome: "Nossa Senhora do Livramento" },
   { nome: "Nova Bandeirantes" },
   { nome: "Nova Brasilândia" },
   { nome: "Nova Canãa do Norte" },
   { nome: "Nova Guarita" },
   { nome: "Nova Lacerda" },
   { nome: "Nova Marilândia" },
   { nome: "Nova Maringá" },
   { nome: "Nova Monte Verde" },
   { nome: "Nova Mutum" },
   { nome: "Nova Nazaré" },
   { nome: "Nova Olímpia" },
   { nome: "Nova Santa Helena" },
   { nome: "Nova Ubiratã" },
   { nome: "Nova Xavantina" },
   { nome: "Novo Horizonte do Norte" },
   { nome: "Novo Mundo" },
   { nome: "Novo Santo Antônio" },
   { nome: "Novo São Joaquim" },
   { nome: "Paranaíta" },
   { nome: "Paranatinga" },
   { nome: "Pedra Preta" },
   { nome: "Peixoto de Azevedo" },
   { nome: "Planalto da Serra" },
   { nome: "Poconé" },
   { nome: "Pontal do Araguaia" },
   { nome: "Ponte Branca" },
   { nome: "Pontes e Lacerda" },
   { nome: "Porto Alegre do Norte" },
   { nome: "Porto dos Gaúchos" },
   { nome: "Porto Esperidião" },
   { nome: "Porto Estrela" },
   { nome: "Poxoréo" },
   { nome: "Primavera do Leste" },
   { nome: "Querência" },
   { nome: "Reserva do Cabaçal" },
   { nome: "Ribeirão Cascalheira" },
   { nome: "Ribeirãozinho" },
   { nome: "Rio Branco" },
   { nome: "Rondolândia" },
   { nome: "Rondonópolis" },
   { nome: "Rosário Oeste" },
   { nome: "Salto do Céu" },
   { nome: "Santa Carmem" },
   { nome: "Santa Cruz do Xingu" },
   { nome: "Santa Rita do Trivelato" },
   { nome: "Santa Terezinha" },
   { nome: "Santo Afonso" },
   { nome: "Santo Antônio do Leste" },
   { nome: "Santo Antônio do Leverger" },
   { nome: "São Félix do Araguaia" },
   { nome: "São José do Povo" },
   { nome: "São José do Rio Claro" },
   { nome: "São José do Xingu" },
   { nome: "São José dos Quatro Marcos" },
   { nome: "São Pedro da Cipa" },
   { nome: "Sapezal" },
   { nome: "Serra Nova Dourada" },
   { nome: "Sinop" },
   { nome: "Sorriso" },
   { nome: "Tabaporã" },
   { nome: "Tangará da Serra" },
   { nome: "Tapurah" },
   { nome: "Terra Nova do Norte" },
   { nome: "Tesouro" },
   { nome: "Torixoréu" },
   { nome: "União do Sul" },
   { nome: "Vale de São Domingos" },
   { nome: "Várzea Grande" },
   { nome: "Vera" },
   { nome: "Vila Bela da Santíssima Trindade" },
   { nome: "Vila Rica" }
  ]
)