PA = Estado.find_by_sigla("PA")
PA.cidades.create(
  [
   { nome: "Abaetetuba" },
   { nome: "Abel Figueiredo" },
   { nome: "Acará" },
   { nome: "Afuá" },
   { nome: "Água Azul do Norte" },
   { nome: "Alenquer" },
   { nome: "Almeirim" },
   { nome: "Altamira" },
   { nome: "Anajás" },
   { nome: "Ananindeua" },
   { nome: "Anapu" },
   { nome: "Augusto Corrêa" },
   { nome: "Aurora do Pará" },
   { nome: "Aveiro" },
   { nome: "Bagre" },
   { nome: "Baião" },
   { nome: "Bannach" },
   { nome: "Barcarena" },
   { nome: "Belém" },
   { nome: "Belterra" },
   { nome: "Benevides" },
   { nome: "Bom Jesus do Tocantins" },
   { nome: "Bonito" },
   { nome: "Bragança" },
   { nome: "Brasil Novo" },
   { nome: "Brejo Grande do Araguaia" },
   { nome: "Breu Branco" },
   { nome: "Breves" },
   { nome: "Bujaru" },
   { nome: "Cachoeira do Arari" },
   { nome: "Cachoeira do Piriá" },
   { nome: "Cametá" },
   { nome: "Canaã dos Carajás" },
   { nome: "Capanema" },
   { nome: "Capitão Poço" },
   { nome: "Castanhal" },
   { nome: "Chaves" },
   { nome: "Colares" },
   { nome: "Conceição do Araguaia" },
   { nome: "Concórdia do Pará" },
   { nome: "Cumaru do Norte" },
   { nome: "Curionópolis" },
   { nome: "Curralinho" },
   { nome: "Curuá" },
   { nome: "Curuçá" },
   { nome: "Dom Eliseu" },
   { nome: "Eldorado dos Carajás" },
   { nome: "Faro" },
   { nome: "Floresta do Araguaia" },
   { nome: "Garrafão do Norte" },
   { nome: "Goianésia do Pará" },
   { nome: "Gurupá" },
   { nome: "Igarapé-Açu" },
   { nome: "Igarapé-Miri" },
   { nome: "Inhangapi" },
   { nome: "Ipixuna do Pará" },
   { nome: "Irituia" },
   { nome: "Itaituba" },
   { nome: "Itupiranga" },
   { nome: "Jacareacanga" },
   { nome: "Jacundá" },
   { nome: "Juruti" },
   { nome: "Limoeiro do Ajuru" },
   { nome: "Mãe do Rio" },
   { nome: "Magalhães Barata" },
   { nome: "Marabá" },
   { nome: "Maracanã" },
   { nome: "Marapanim" },
   { nome: "Marituba" },
   { nome: "Medicilândia" },
   { nome: "Melgaço" },
   { nome: "Mocajuba" },
   { nome: "Moju" },
   { nome: "Monte Alegre" },
   { nome: "Muaná" },
   { nome: "Nova Esperança do Piriá" },
   { nome: "Nova Ipixuna" },
   { nome: "Nova Timboteua" },
   { nome: "Novo Progresso" },
   { nome: "Novo Repartimento" },
   { nome: "Óbidos" },
   { nome: "Oeiras do Pará" },
   { nome: "Oriximiná" },
   { nome: "Ourém" },
   { nome: "Ourilândia do Norte" },
   { nome: "Pacajá" },
   { nome: "Palestina do Pará" },
   { nome: "Paragominas" },
   { nome: "Parauapebas" },
   { nome: "Pau d'Arco" },
   { nome: "Peixe-Boi" },
   { nome: "Piçarra" },
   { nome: "Placas" },
   { nome: "Ponta de Pedras" },
   { nome: "Portel" },
   { nome: "Porto de Moz" },
   { nome: "Prainha" },
   { nome: "Primavera" },
   { nome: "Quatipuru" },
   { nome: "Redenção" },
   { nome: "Rio Maria" },
   { nome: "Rondon do Pará" },
   { nome: "Rurópolis" },
   { nome: "Salinópolis" },
   { nome: "Salvaterra" },
   { nome: "Santa Bárbara do Pará" },
   { nome: "Santa Cruz do Arari" },
   { nome: "Santa Isabel do Pará" },
   { nome: "Santa Luzia do Pará" },
   { nome: "Santa Maria das Barreiras" },
   { nome: "Santa Maria do Pará" },
   { nome: "Santana do Araguaia" },
   { nome: "Santarém" },
   { nome: "Santarém Novo" },
   { nome: "Santo Antônio do Tauá" },
   { nome: "São Caetano de Odivela" },
   { nome: "São Domingos do Araguaia" },
   { nome: "São Domingos do Capim" },
   { nome: "São Félix do Xingu" },
   { nome: "São Francisco do Pará" },
   { nome: "São Geraldo do Araguaia" },
   { nome: "São João da Ponta" },
   { nome: "São João de Pirabas" },
   { nome: "São João do Araguaia" },
   { nome: "São Miguel do Guamá" },
   { nome: "São Sebastião da Boa Vista" },
   { nome: "Sapucaia" },
   { nome: "Senador José Porfírio" },
   { nome: "Soure" },
   { nome: "Tailândia" },
   { nome: "Terra Alta" },
   { nome: "Terra Santa" },
   { nome: "Tomé-Açu" },
   { nome: "Tracuateua" },
   { nome: "Trairão" },
   { nome: "Tucumã" },
   { nome: "Tucuruí" },
   { nome: "Ulianópolis" },
   { nome: "Uruará" },
   { nome: "Vigia" },
   { nome: "Viseu" },
   { nome: "Vitória do Xingu" },
   { nome: "Xinguara" }
  ]
)