PI = Estado.find_by_sigla("PI")
PI.cidades.create(
  [
   { nome: "Acauã" },
   { nome: "Agricolândia" },
   { nome: "Água Branca" },
   { nome: "Alagoinha do Piauí" },
   { nome: "Alegrete do Piauí" },
   { nome: "Alto Longá" },
   { nome: "Altos" },
   { nome: "Alvorada do Gurguéia" },
   { nome: "Amarante" },
   { nome: "Angical do Piauí" },
   { nome: "Anísio de Abreu" },
   { nome: "Antônio Almeida" },
   { nome: "Aroazes" },
   { nome: "Arraial" },
   { nome: "Assunção do Piauí" },
   { nome: "Avelino Lopes" },
   { nome: "Baixa Grande do Ribeiro" },
   { nome: "Barra d'Alcântara" },
   { nome: "Barras" },
   { nome: "Barreiras do Piauí" },
   { nome: "Barro Duro" },
   { nome: "Batalha" },
   { nome: "Bela Vista do Piauí" },
   { nome: "Belém do Piauí" },
   { nome: "Beneditinos" },
   { nome: "Bertolínia" },
   { nome: "Betânia do Piauí" },
   { nome: "Boa Hora" },
   { nome: "Bocaina" },
   { nome: "Bom Jesus" },
   { nome: "Bom Princípio do Piauí" },
   { nome: "Bonfim do Piauí" },
   { nome: "Boqueirão do Piauí" },
   { nome: "Brasileira" },
   { nome: "Brejo do Piauí" },
   { nome: "Buriti dos Lopes" },
   { nome: "Buriti dos Montes" },
   { nome: "Cabeceiras do Piauí" },
   { nome: "Cajazeiras do Piauí" },
   { nome: "Cajueiro da Praia" },
   { nome: "Caldeirão Grande do Piauí" },
   { nome: "Campinas do Piauí" },
   { nome: "Campo Alegre do Fidalgo" },
   { nome: "Campo Grande do Piauí" },
   { nome: "Campo Largo do Piauí" },
   { nome: "Campo Maior" },
   { nome: "Canavieira" },
   { nome: "Canto do Buriti" },
   { nome: "Capitão de Campos" },
   { nome: "Capitão Gervásio Oliveira" },
   { nome: "Caracol" },
   { nome: "Caraúbas do Piauí" },
   { nome: "Caridade do Piauí" },
   { nome: "Castelo do Piauí" },
   { nome: "Caxingó" },
   { nome: "Cocal" },
   { nome: "Cocal de Telha" },
   { nome: "Cocal dos Alves" },
   { nome: "Coivaras" },
   { nome: "Colônia do Gurguéia" },
   { nome: "Colônia do Piauí" },
   { nome: "Conceição do Canindé" },
   { nome: "Coronel José Dias" },
   { nome: "Corrente" },
   { nome: "Cristalândia do Piauí" },
   { nome: "Cristino Castro" },
   { nome: "Curimatá" },
   { nome: "Currais" },
   { nome: "Curral Novo do Piauí" },
   { nome: "Curralinhos" },
   { nome: "Demerval Lobão" },
   { nome: "Dirceu Arcoverde" },
   { nome: "Dom Expedito Lopes" },
   { nome: "Dom Inocêncio" },
   { nome: "Domingos Mourão" },
   { nome: "Elesbão Veloso" },
   { nome: "Eliseu Martins" },
   { nome: "Esperantina" },
   { nome: "Fartura do Piauí" },
   { nome: "Flores do Piauí" },
   { nome: "Floresta do Piauí" },
   { nome: "Floriano" },
   { nome: "Francinópolis" },
   { nome: "Francisco Ayres" },
   { nome: "Francisco Macedo" },
   { nome: "Francisco Santos" },
   { nome: "Fronteiras" },
   { nome: "Geminiano" },
   { nome: "Gilbués" },
   { nome: "Guadalupe" },
   { nome: "Guaribas" },
   { nome: "Hugo Napoleão" },
   { nome: "Ilha Grande" },
   { nome: "Inhuma" },
   { nome: "Ipiranga do Piauí" },
   { nome: "Isaías Coelho" },
   { nome: "Itainópolis" },
   { nome: "Itaueira" },
   { nome: "Jacobina do Piauí" },
   { nome: "Jaicós" },
   { nome: "Jardim do Mulato" },
   { nome: "Jatobá do Piauí" },
   { nome: "Jerumenha" },
   { nome: "João Costa" },
   { nome: "Joaquim Pires" },
   { nome: "Joca Marques" },
   { nome: "José de Freitas" },
   { nome: "Juazeiro do Piauí" },
   { nome: "Júlio Borges" },
   { nome: "Jurema" },
   { nome: "Lagoa Alegre" },
   { nome: "Lagoa de São Francisco" },
   { nome: "Lagoa do Barro do Piauí" },
   { nome: "Lagoa do Piauí" },
   { nome: "Lagoa do Sítio" },
   { nome: "Lagoinha do Piauí" },
   { nome: "Landri Sales" },
   { nome: "Luís Correia" },
   { nome: "Luzilândia" },
   { nome: "Madeiro" },
   { nome: "Manoel Emídio" },
   { nome: "Marcolândia" },
   { nome: "Marcos Parente" },
   { nome: "Massapê do Piauí" },
   { nome: "Matias Olímpio" },
   { nome: "Miguel Alves" },
   { nome: "Miguel Leão" },
   { nome: "Milton Brandão" },
   { nome: "Monsenhor Gil" },
   { nome: "Monsenhor Hipólito" },
   { nome: "Monte Alegre do Piauí" },
   { nome: "Morro Cabeça no Tempo" },
   { nome: "Morro do Chapéu do Piauí" },
   { nome: "Murici dos Portelas" },
   { nome: "Nazaré do Piauí" },
   { nome: "Nossa Senhora de Nazaré" },
   { nome: "Nossa Senhora dos Remédios" },
   { nome: "Nova Santa Rita" },
   { nome: "Novo Oriente do Piauí" },
   { nome: "Novo Santo Antônio" },
   { nome: "Oeiras" },
   { nome: "Olho d'Água do Piauí" },
   { nome: "Padre Marcos" },
   { nome: "Paes Landim" },
   { nome: "Pajeú do Piauí" },
   { nome: "Palmeira do Piauí" },
   { nome: "Palmeirais" },
   { nome: "Paquetá" },
   { nome: "Parnaguá" },
   { nome: "Parnaíba" },
   { nome: "Passagem Franca do Piauí" },
   { nome: "Patos do Piauí" },
   { nome: "Pau d'Arco do Piauí" },
   { nome: "Paulistana" },
   { nome: "Pavussu" },
   { nome: "Pedro II" },
   { nome: "Pedro Laurentino" },
   { nome: "Picos" },
   { nome: "Pimenteiras" },
   { nome: "Pio IX" },
   { nome: "Piracuruca" },
   { nome: "Piripiri" },
   { nome: "Porto" },
   { nome: "Porto Alegre do Piauí" },
   { nome: "Prata do Piauí" },
   { nome: "Queimada Nova" },
   { nome: "Redenção do Gurguéia" },
   { nome: "Regeneração" },
   { nome: "Riacho Frio" },
   { nome: "Ribeira do Piauí" },
   { nome: "Ribeiro Gonçalves" },
   { nome: "Rio Grande do Piauí" },
   { nome: "Santa Cruz do Piauí" },
   { nome: "Santa Cruz dos Milagres" },
   { nome: "Santa Filomena" },
   { nome: "Santa Luz" },
   { nome: "Santa Rosa do Piauí" },
   { nome: "Santana do Piauí" },
   { nome: "Santo Antônio de Lisboa" },
   { nome: "Santo Antônio dos Milagres" },
   { nome: "Santo Inácio do Piauí" },
   { nome: "São Braz do Piauí" },
   { nome: "São Félix do Piauí" },
   { nome: "São Francisco de Assis do Piauí" },
   { nome: "São Francisco do Piauí" },
   { nome: "São Gonçalo do Gurguéia" },
   { nome: "São Gonçalo do Piauí" },
   { nome: "São João da Canabrava" },
   { nome: "São João da Fronteira" },
   { nome: "São João da Serra" },
   { nome: "São João da Varjota" },
   { nome: "São João do Arraial" },
   { nome: "São João do Piauí" },
   { nome: "São José do Divino" },
   { nome: "São José do Peixe" },
   { nome: "São José do Piauí" },
   { nome: "São Julião" },
   { nome: "São Lourenço do Piauí" },
   { nome: "São Luis do Piauí" },
   { nome: "São Miguel da Baixa Grande" },
   { nome: "São Miguel do Fidalgo" },
   { nome: "São Miguel do Tapuio" },
   { nome: "São Pedro do Piauí" },
   { nome: "São Raimundo Nonato" },
   { nome: "Sebastião Barros" },
   { nome: "Sebastião Leal" },
   { nome: "Sigefredo Pacheco" },
   { nome: "Simões" },
   { nome: "Simplício Mendes" },
   { nome: "Socorro do Piauí" },
   { nome: "Sussuapara" },
   { nome: "Tamboril do Piauí" },
   { nome: "Tanque do Piauí" },
   { nome: "Teresina" },
   { nome: "União" },
   { nome: "Uruçuí" },
   { nome: "Valença do Piauí" },
   { nome: "Várzea Branca" },
   { nome: "Várzea Grande" },
   { nome: "Vera Mendes" },
   { nome: "Vila Nova do Piauí" },
   { nome: "Wall Ferraz" }
  ]
)