PR = Estado.find_by_sigla("PR")
PR.cidades.create(
  [
   { nome: "Abatiá" },
   { nome: "Adrianópolis" },
   { nome: "Agudos do Sul" },
   { nome: "Almirante Tamandaré" },
   { nome: "Altamira do Paraná" },
   { nome: "Alto Paraná" },
   { nome: "Alto Piquiri" },
   { nome: "Altônia" },
   { nome: "Alvorada do Sul" },
   { nome: "Amaporã" },
   { nome: "Ampére" },
   { nome: "Anahy" },
   { nome: "Andirá" },
   { nome: "Ângulo" },
   { nome: "Antonina" },
   { nome: "Antônio Olinto" },
   { nome: "Apucarana" },
   { nome: "Arapongas" },
   { nome: "Arapoti" },
   { nome: "Arapuã" },
   { nome: "Araruna" },
   { nome: "Araucária" },
   { nome: "Ariranha do Ivaí" },
   { nome: "Assaí" },
   { nome: "Assis Chateaubriand" },
   { nome: "Astorga" },
   { nome: "Atalaia" },
   { nome: "Balsa Nova" },
   { nome: "Bandeirantes" },
   { nome: "Barbosa Ferraz" },
   { nome: "Barra do Jacaré" },
   { nome: "Barracão" },
   { nome: "Bela Vista da Caroba" },
   { nome: "Bela Vista do Paraíso" },
   { nome: "Bituruna" },
   { nome: "Boa Esperança" },
   { nome: "Boa Esperança do Iguaçu" },
   { nome: "Boa Ventura de São Roque" },
   { nome: "Boa Vista da Aparecida" },
   { nome: "Bocaiúva do Sul" },
   { nome: "Bom Jesus do Sul" },
   { nome: "Bom Sucesso" },
   { nome: "Bom Sucesso do Sul" },
   { nome: "Borrazópolis" },
   { nome: "Braganey" },
   { nome: "Brasilândia do Sul" },
   { nome: "Cafeara" },
   { nome: "Cafelândia" },
   { nome: "Cafezal do Sul" },
   { nome: "Califórnia" },
   { nome: "Cambará" },
   { nome: "Cambé" },
   { nome: "Cambira" },
   { nome: "Campina da Lagoa" },
   { nome: "Campina do Simão" },
   { nome: "Campina Grande do Sul" },
   { nome: "Campo Bonito" },
   { nome: "Campo do Tenente" },
   { nome: "Campo Largo" },
   { nome: "Campo Magro" },
   { nome: "Campo Mourão" },
   { nome: "Cândido de Abreu" },
   { nome: "Candói" },
   { nome: "Cantagalo" },
   { nome: "Capanema" },
   { nome: "Capitão Leônidas Marques" },
   { nome: "Carambeí" },
   { nome: "Carlópolis" },
   { nome: "Cascavel" },
   { nome: "Castro" },
   { nome: "Catanduvas" },
   { nome: "Centenário do Sul" },
   { nome: "Cerro Azul" },
   { nome: "Céu Azul" },
   { nome: "Chopinzinho" },
   { nome: "Cianorte" },
   { nome: "Cidade Gaúcha" },
   { nome: "Clevelândia" },
   { nome: "Colombo" },
   { nome: "Colorado" },
   { nome: "Congonhinhas" },
   { nome: "Conselheiro Mairinck" },
   { nome: "Contenda" },
   { nome: "Corbélia" },
   { nome: "Cornélio Procópio" },
   { nome: "Coronel Domingos Soares" },
   { nome: "Coronel Vivida" },
   { nome: "Corumbataí do Sul" },
   { nome: "Cruz Machado" },
   { nome: "Cruzeiro do Iguaçu" },
   { nome: "Cruzeiro do Oeste" },
   { nome: "Cruzeiro do Sul" },
   { nome: "Cruzmaltina" },
   { nome: "Curitiba" },
   { nome: "Curiúva" },
   { nome: "Diamante d'Oeste" },
   { nome: "Diamante do Norte" },
   { nome: "Diamante do Sul" },
   { nome: "Dois Vizinhos" },
   { nome: "Douradina" },
   { nome: "Doutor Camargo" },
   { nome: "Doutor Ulysses" },
   { nome: "Enéas Marques" },
   { nome: "Engenheiro Beltrão" },
   { nome: "Entre Rios do Oeste" },
   { nome: "Esperança Nova" },
   { nome: "Espigão Alto do Iguaçu" },
   { nome: "Farol" },
   { nome: "Faxinal" },
   { nome: "Fazenda Rio Grande" },
   { nome: "Fênix" },
   { nome: "Fernandes Pinheiro" },
   { nome: "Figueira" },
   { nome: "Flor da Serra do Sul" },
   { nome: "Floraí" },
   { nome: "Floresta" },
   { nome: "Florestópolis" },
   { nome: "Flórida" },
   { nome: "Formosa do Oeste" },
   { nome: "Foz do Iguaçu" },
   { nome: "Foz do Jordão" },
   { nome: "Francisco Alves" },
   { nome: "Francisco Beltrão" },
   { nome: "General Carneiro" },
   { nome: "Godoy Moreira" },
   { nome: "Goioerê" },
   { nome: "Goioxim" },
   { nome: "Grandes Rios" },
   { nome: "Guaíra" },
   { nome: "Guairaçá" },
   { nome: "Guamiranga" },
   { nome: "Guapirama" },
   { nome: "Guaporema" },
   { nome: "Guaraci" },
   { nome: "Guaraniaçu" },
   { nome: "Guarapuava" },
   { nome: "Guaraqueçaba" },
   { nome: "Guaratuba" },
   { nome: "Honório Serpa" },
   { nome: "Ibaiti" },
   { nome: "Ibema" },
   { nome: "Ibiporã" },
   { nome: "Icaraíma" },
   { nome: "Iguaraçu" },
   { nome: "Iguatu" },
   { nome: "Imbaú" },
   { nome: "Imbituva" },
   { nome: "Inácio Martins" },
   { nome: "Inajá" },
   { nome: "Indianópolis" },
   { nome: "Ipiranga" },
   { nome: "Iporã" },
   { nome: "Iracema do Oeste" },
   { nome: "Irati" },
   { nome: "Iretama" },
   { nome: "Itaguajé" },
   { nome: "Itaipulândia" },
   { nome: "Itambaracá" },
   { nome: "Itambé" },
   { nome: "Itapejara d'Oeste" },
   { nome: "Itaperuçu" },
   { nome: "Itaúna do Sul" },
   { nome: "Ivaí" },
   { nome: "Ivaiporã" },
   { nome: "Ivaté" },
   { nome: "Ivatuba" },
   { nome: "Jaboti" },
   { nome: "Jacarezinho" },
   { nome: "Jaguapitã" },
   { nome: "Jaguariaíva" },
   { nome: "Jandaia do Sul" },
   { nome: "Janiópolis" },
   { nome: "Japira" },
   { nome: "Japurá" },
   { nome: "Jardim Alegre" },
   { nome: "Jardim Olinda" },
   { nome: "Jataizinho" },
   { nome: "Jesuítas" },
   { nome: "Joaquim Távora" },
   { nome: "Jundiaí do Sul" },
   { nome: "Juranda" },
   { nome: "Jussara" },
   { nome: "Kaloré" },
   { nome: "Lapa" },
   { nome: "Laranjal" },
   { nome: "Laranjeiras do Sul" },
   { nome: "Leópolis" },
   { nome: "Lidianópolis" },
   { nome: "Lindoeste" },
   { nome: "Loanda" },
   { nome: "Lobato" },
   { nome: "Londrina" },
   { nome: "Luiziana" },
   { nome: "Lunardelli" },
   { nome: "Lupionópolis" },
   { nome: "Mallet" },
   { nome: "Mamborê" },
   { nome: "Mandaguaçu" },
   { nome: "Mandaguari" },
   { nome: "Mandirituba" },
   { nome: "Manfrinópolis" },
   { nome: "Mangueirinha" },
   { nome: "Manoel Ribas" },
   { nome: "Marechal Cândido Rondon" },
   { nome: "Maria Helena" },
   { nome: "Marialva" },
   { nome: "Marilândia do Sul" },
   { nome: "Marilena" },
   { nome: "Mariluz" },
   { nome: "Maringá" },
   { nome: "Mariópolis" },
   { nome: "Maripá" },
   { nome: "Marmeleiro" },
   { nome: "Marquinho" },
   { nome: "Marumbi" },
   { nome: "Matelândia" },
   { nome: "Matinhos" },
   { nome: "Mato Rico" },
   { nome: "Mauá da Serra" },
   { nome: "Medianeira" },
   { nome: "Mercedes" },
   { nome: "Mirador" },
   { nome: "Miraselva" },
   { nome: "Missal" },
   { nome: "Moreira Sales" },
   { nome: "Morretes" },
   { nome: "Munhoz de Melo" },
   { nome: "Nossa Senhora das Graças" },
   { nome: "Nova Aliança do Ivaí" },
   { nome: "Nova América da Colina" },
   { nome: "Nova Aurora" },
   { nome: "Nova Cantu" },
   { nome: "Nova Esperança" },
   { nome: "Nova Esperança do Sudoeste" },
   { nome: "Nova Fátima" },
   { nome: "Nova Laranjeiras" },
   { nome: "Nova Londrina" },
   { nome: "Nova Olímpia" },
   { nome: "Nova Prata do Iguaçu" },
   { nome: "Nova Santa Bárbara" },
   { nome: "Nova Santa Rosa" },
   { nome: "Nova Tebas" },
   { nome: "Novo Itacolomi" },
   { nome: "Ortigueira" },
   { nome: "Ourizona" },
   { nome: "Ouro Verde do Oeste" },
   { nome: "Paiçandu" },
   { nome: "Palmas" },
   { nome: "Palmeira" },
   { nome: "Palmital" },
   { nome: "Palotina" },
   { nome: "Paraíso do Norte" },
   { nome: "Paranacity" },
   { nome: "Paranaguá" },
   { nome: "Paranapoema" },
   { nome: "Paranavaí" },
   { nome: "Pato Bragado" },
   { nome: "Pato Branco" },
   { nome: "Paula Freitas" },
   { nome: "Paulo Frontin" },
   { nome: "Peabiru" },
   { nome: "Perobal" },
   { nome: "Pérola" },
   { nome: "Pérola d'Oeste" },
   { nome: "Piên" },
   { nome: "Pinhais" },
   { nome: "Pinhal de São Bento" },
   { nome: "Pinhalão" },
   { nome: "Pinhão" },
   { nome: "Piraí do Sul" },
   { nome: "Piraquara" },
   { nome: "Pitanga" },
   { nome: "Pitangueiras" },
   { nome: "Planaltina do Paraná" },
   { nome: "Planalto" },
   { nome: "Ponta Grossa" },
   { nome: "Pontal do Paraná" },
   { nome: "Porecatu" },
   { nome: "Porto Amazonas" },
   { nome: "Porto Barreiro" },
   { nome: "Porto Rico" },
   { nome: "Porto Vitória" },
   { nome: "Prado Ferreira" },
   { nome: "Pranchita" },
   { nome: "Presidente Castelo Branco" },
   { nome: "Primeiro de Maio" },
   { nome: "Prudentópolis" },
   { nome: "Quarto Centenário" },
   { nome: "Quatiguá" },
   { nome: "Quatro Barras" },
   { nome: "Quatro Pontes" },
   { nome: "Quedas do Iguaçu" },
   { nome: "Querência do Norte" },
   { nome: "Quinta do Sol" },
   { nome: "Quitandinha" },
   { nome: "Ramilândia" },
   { nome: "Rancho Alegre" },
   { nome: "Rancho Alegre d'Oeste" },
   { nome: "Realeza" },
   { nome: "Rebouças" },
   { nome: "Renascença" },
   { nome: "Reserva" },
   { nome: "Reserva do Iguaçu" },
   { nome: "Ribeirão Claro" },
   { nome: "Ribeirão do Pinhal" },
   { nome: "Rio Azul" },
   { nome: "Rio Bom" },
   { nome: "Rio Bonito do Iguaçu" },
   { nome: "Rio Branco do Ivaí" },
   { nome: "Rio Branco do Sul" },
   { nome: "Rio Negro" },
   { nome: "Rolândia" },
   { nome: "Roncador" },
   { nome: "Rondon" },
   { nome: "Rosário do Ivaí" },
   { nome: "Sabáudia" },
   { nome: "Salgado Filho" },
   { nome: "Salto do Itararé" },
   { nome: "Salto do Lontra" },
   { nome: "Santa Amélia" },
   { nome: "Santa Cecília do Pavão" },
   { nome: "Santa Cruz Monte Castelo" },
   { nome: "Santa Fé" },
   { nome: "Santa Helena" },
   { nome: "Santa Inês" },
   { nome: "Santa Isabel do Ivaí" },
   { nome: "Santa Izabel do Oeste" },
   { nome: "Santa Lúcia" },
   { nome: "Santa Maria do Oeste" },
   { nome: "Santa Mariana" },
   { nome: "Santa Mônica" },
   { nome: "Santa Tereza do Oeste" },
   { nome: "Santa Terezinha de Itaipu" },
   { nome: "Santana do Itararé" },
   { nome: "Santo Antônio da Platina" },
   { nome: "Santo Antônio do Caiuá" },
   { nome: "Santo Antônio do Paraíso" },
   { nome: "Santo Antônio do Sudoeste" },
   { nome: "Santo Inácio" },
   { nome: "São Carlos do Ivaí" },
   { nome: "São Jerônimo da Serra" },
   { nome: "São João" },
   { nome: "São João do Caiuá" },
   { nome: "São João do Ivaí" },
   { nome: "São João do Triunfo" },
   { nome: "São Jorge d'Oeste" },
   { nome: "São Jorge do Ivaí" },
   { nome: "São Jorge do Patrocínio" },
   { nome: "São José da Boa Vista" },
   { nome: "São José das Palmeiras" },
   { nome: "São José dos Pinhais" },
   { nome: "São Manoel do Paraná" },
   { nome: "São Mateus do Sul" },
   { nome: "São Miguel do Iguaçu" },
   { nome: "São Pedro do Iguaçu" },
   { nome: "São Pedro do Ivaí" },
   { nome: "São Pedro do Paraná" },
   { nome: "São Sebastião da Amoreira" },
   { nome: "São Tomé" },
   { nome: "Sapopema" },
   { nome: "Sarandi" },
   { nome: "Saudade do Iguaçu" },
   { nome: "Sengés" },
   { nome: "Serranópolis do Iguaçu" },
   { nome: "Sertaneja" },
   { nome: "Sertanópolis" },
   { nome: "Siqueira Campos" },
   { nome: "Sulina" },
   { nome: "Tamarana" },
   { nome: "Tamboara" },
   { nome: "Tapejara" },
   { nome: "Tapira" },
   { nome: "Teixeira Soares" },
   { nome: "Telêmaco Borba" },
   { nome: "Terra Boa" },
   { nome: "Terra Rica" },
   { nome: "Terra Roxa" },
   { nome: "Tibagi" },
   { nome: "Tijucas do Sul" },
   { nome: "Toledo" },
   { nome: "Tomazina" },
   { nome: "Três Barras do Paraná" },
   { nome: "Tunas do Paraná" },
   { nome: "Tuneiras do Oeste" },
   { nome: "Tupãssi" },
   { nome: "Turvo" },
   { nome: "Ubiratã" },
   { nome: "Umuarama" },
   { nome: "União da Vitória" },
   { nome: "Uniflor" },
   { nome: "Uraí" },
   { nome: "Ventania" },
   { nome: "Vera Cruz do Oeste" },
   { nome: "Verê" },
   { nome: "Vila Alta" },
   { nome: "Virmond" },
   { nome: "Vitorino" },
   { nome: "Wenceslau Braz" },
   { nome: "Xambrê" }
  ]
)