RJ = Estado.find_by_sigla("RJ")
RJ.cidades.create(
  [
   { nome: "Angra dos Reis" },
   { nome: "Aperibé" },
   { nome: "Araruama" },
   { nome: "Areal" },
   { nome: "Armação de Búzios" },
   { nome: "Arraial do Cabo" },
   { nome: "Barra do Piraí" },
   { nome: "Barra Mansa" },
   { nome: "Belford Roxo" },
   { nome: "Bom Jardim" },
   { nome: "Bom Jesus do Itabapoana" },
   { nome: "Cabo Frio" },
   { nome: "Cachoeiras de Macacu" },
   { nome: "Cambuci" },
   { nome: "Campos dos Goytacazes" },
   { nome: "Cantagalo" },
   { nome: "Carapebus" },
   { nome: "Cardoso Moreira" },
   { nome: "Carmo" },
   { nome: "Casimiro de Abreu" },
   { nome: "Comendador Levy Gasparian" },
   { nome: "Conceição de Macabu" },
   { nome: "Cordeiro" },
   { nome: "Duas Barras" },
   { nome: "Duque de Caxias" },
   { nome: "Engenheiro Paulo de Frontin" },
   { nome: "Guapimirim" },
   { nome: "Iguaba Grande" },
   { nome: "Itaboraí" },
   { nome: "Itaguaí" },
   { nome: "Italva" },
   { nome: "Itaocara" },
   { nome: "Itaperuna" },
   { nome: "Itatiaia" },
   { nome: "Japeri" },
   { nome: "Laje do Muriaé" },
   { nome: "Macaé" },
   { nome: "Macuco" },
   { nome: "Magé" },
   { nome: "Mangaratiba" },
   { nome: "Maricá" },
   { nome: "Mendes" },
   { nome: "Mesquita" },
   { nome: "Miguel Pereira" },
   { nome: "Miracema" },
   { nome: "Natividade" },
   { nome: "Nilópolis" },
   { nome: "Niterói" },
   { nome: "Nova Friburgo" },
   { nome: "Nova Iguaçu" },
   { nome: "Paracambi" },
   { nome: "Paraíba do Sul" },
   { nome: "Parati" },
   { nome: "Paty do Alferes" },
   { nome: "Petrópolis" },
   { nome: "Pinheiral" },
   { nome: "Piraí" },
   { nome: "Porciúncula" },
   { nome: "Porto Real" },
   { nome: "Quatis" },
   { nome: "Queimados" },
   { nome: "Quissamã" },
   { nome: "Resende" },
   { nome: "Rio Bonito" },
   { nome: "Rio Claro" },
   { nome: "Rio das Flores" },
   { nome: "Rio das Ostras" },
   { nome: "Rio de Janeiro" },
   { nome: "Santa Maria Madalena" },
   { nome: "Santo Antônio de Pádua" },
   { nome: "São Fidélis" },
   { nome: "São Francisco de Itabapoana" },
   { nome: "São Gonçalo" },
   { nome: "São João da Barra" },
   { nome: "São João de Meriti" },
   { nome: "São José de Ubá" },
   { nome: "São José do Vale do Rio Preto" },
   { nome: "São Pedro da Aldeia" },
   { nome: "São Sebastião do Alto" },
   { nome: "Sapucaia" },
   { nome: "Saquarema" },
   { nome: "Seropédica" },
   { nome: "Silva Jardim" },
   { nome: "Sumidouro" },
   { nome: "Tanguá" },
   { nome: "Teresópolis" },
   { nome: "Trajano de Morais" },
   { nome: "Três Rios" },
   { nome: "Valença" },
   { nome: "Varre-Sai" },
   { nome: "Vassouras" },
   { nome: "Volta Redonda" }
  ]
)