RN = Estado.find_by_sigla("RN")
RN.cidades.create(
  [
   { nome: "Acari" },
   { nome: "Açu" },
   { nome: "Afonso Bezerra" },
   { nome: "Água Nova" },
   { nome: "Alexandria" },
   { nome: "Almino Afonso" },
   { nome: "Alto do Rodrigues" },
   { nome: "Angicos" },
   { nome: "Antônio Martins" },
   { nome: "Apodi" },
   { nome: "Areia Branca" },
   { nome: "Arês" },
   { nome: "Augusto Severo" },
   { nome: "Baía Formosa" },
   { nome: "Baraúna" },
   { nome: "Barcelona" },
   { nome: "Bento Fernandes" },
   { nome: "Bodó" },
   { nome: "Bom Jesus" },
   { nome: "Brejinho" },
   { nome: "Caiçara do Norte" },
   { nome: "Caiçara do Rio do Vento" },
   { nome: "Caicó" },
   { nome: "Campo Redondo" },
   { nome: "Canguaretama" },
   { nome: "Caraúbas" },
   { nome: "Carnaúba dos Dantas" },
   { nome: "Carnaubais" },
   { nome: "Ceará-Mirim" },
   { nome: "Cerro Corá" },
   { nome: "Coronel Ezequiel" },
   { nome: "Coronel João Pessoa" },
   { nome: "Cruzeta" },
   { nome: "Currais Novos" },
   { nome: "Doutor Severiano" },
   { nome: "Encanto" },
   { nome: "Equador" },
   { nome: "Espírito Santo" },
   { nome: "Extremoz" },
   { nome: "Felipe Guerra" },
   { nome: "Fernando Pedroza" },
   { nome: "Florânia" },
   { nome: "Francisco Dantas" },
   { nome: "Frutuoso Gomes" },
   { nome: "Galinhos" },
   { nome: "Goianinha" },
   { nome: "Governador Dix-Sept Rosado" },
   { nome: "Grossos" },
   { nome: "Guamaré" },
   { nome: "Ielmo Marinho" },
   { nome: "Ipanguaçu" },
   { nome: "Ipueira" },
   { nome: "Itajá" },
   { nome: "Itaú" },
   { nome: "Jaçanã" },
   { nome: "Jandaíra" },
   { nome: "Janduís" },
   { nome: "Januário Cicco" },
   { nome: "Japi" },
   { nome: "Jardim de Angicos" },
   { nome: "Jardim de Piranhas" },
   { nome: "Jardim do Seridó" },
   { nome: "João Câmara" },
   { nome: "João Dias" },
   { nome: "José da Penha" },
   { nome: "Jucurutu" },
   { nome: "Jundiá" },
   { nome: "Lagoa d'Anta" },
   { nome: "Lagoa de Pedras" },
   { nome: "Lagoa de Velhos" },
   { nome: "Lagoa Nova" },
   { nome: "Lagoa Salgada" },
   { nome: "Lajes" },
   { nome: "Lajes Pintadas" },
   { nome: "Lucrécia" },
   { nome: "Luís Gomes" },
   { nome: "Macaíba" },
   { nome: "Macau" },
   { nome: "Major Sales" },
   { nome: "Marcelino Vieira" },
   { nome: "Martins" },
   { nome: "Maxaranguape" },
   { nome: "Messias Targino" },
   { nome: "Montanhas" },
   { nome: "Monte Alegre" },
   { nome: "Monte das Gameleiras" },
   { nome: "Mossoró" },
   { nome: "Natal" },
   { nome: "Nísia Floresta" },
   { nome: "Nova Cruz" },
   { nome: "Olho-d'Água do Borges" },
   { nome: "Ouro Branco" },
   { nome: "Paraná" },
   { nome: "Paraú" },
   { nome: "Parazinho" },
   { nome: "Parelhas" },
   { nome: "Parnamirim" },
   { nome: "Passa e Fica" },
   { nome: "Passagem" },
   { nome: "Patu" },
   { nome: "Pau dos Ferros" },
   { nome: "Pedra Grande" },
   { nome: "Pedra Preta" },
   { nome: "Pedro Avelino" },
   { nome: "Pedro Velho" },
   { nome: "Pendências" },
   { nome: "Pilões" },
   { nome: "Poço Branco" },
   { nome: "Portalegre" },
   { nome: "Porto do Mangue" },
   { nome: "Presidente Juscelino" },
   { nome: "Pureza" },
   { nome: "Rafael Fernandes" },
   { nome: "Rafael Godeiro" },
   { nome: "Riacho da Cruz" },
   { nome: "Riacho de Santana" },
   { nome: "Riachuelo" },
   { nome: "Rio do Fogo" },
   { nome: "Rodolfo Fernandes" },
   { nome: "Ruy Barbosa" },
   { nome: "Santa Cruz" },
   { nome: "Santa Maria" },
   { nome: "Santana do Matos" },
   { nome: "Santana do Seridó" },
   { nome: "Santo Antônio" },
   { nome: "São Bento do Norte" },
   { nome: "São Bento do Trairí" },
   { nome: "São Fernando" },
   { nome: "São Francisco do Oeste" },
   { nome: "São Gonçalo do Amarante" },
   { nome: "São João do Sabugi" },
   { nome: "São José de Mipibu" },
   { nome: "São José do Campestre" },
   { nome: "São José do Seridó" },
   { nome: "São Miguel" },
   { nome: "São Miguel de Touros" },
   { nome: "São Paulo do Potengi" },
   { nome: "São Pedro" },
   { nome: "São Rafael" },
   { nome: "São Tomé" },
   { nome: "São Vicente" },
   { nome: "Senador Elói de Souza" },
   { nome: "Senador Georgino Avelino" },
   { nome: "Serra de São Bento" },
   { nome: "Serra do Mel" },
   { nome: "Serra Negra do Norte" },
   { nome: "Serrinha" },
   { nome: "Serrinha dos Pintos" },
   { nome: "Severiano Melo" },
   { nome: "Sítio Novo" },
   { nome: "Taboleiro Grande" },
   { nome: "Taipu" },
   { nome: "Tangará" },
   { nome: "Tenente Ananias" },
   { nome: "Tenente Laurentino Cruz" },
   { nome: "Tibau" },
   { nome: "Tibau do Sul" },
   { nome: "Timbaúba dos Batistas" },
   { nome: "Touros" },
   { nome: "Triunfo Potiguar" },
   { nome: "Umarizal" },
   { nome: "Upanema" },
   { nome: "Várzea" },
   { nome: "Venha-Ver" },
   { nome: "Vera Cruz" },
   { nome: "Viçosa" },
   { nome: "Vila Flor" }
  ]
)