RO = Estado.find_by_sigla("RO")
RO.cidades.create(
  [
     { nome: "Alta Floresta d'Oeste" },
     { nome: "Alto Alegre do Parecis" },
     { nome: "Alto Paraíso" },
     { nome: "Alvorada d'Oeste" },
     { nome: "Ariquemes" },
     { nome: "Buritis" },
     { nome: "Cabixi" },
     { nome: "Cacaulândia" },
     { nome: "Cacoal" },
     { nome: "Campo Novo de Rondônia" },
     { nome: "Candeias do Jamari" },
     { nome: "Castanheiras" },
     { nome: "Cerejeiras" },
     { nome: "Chupinguaia" },
     { nome: "Colorado do Oeste" },
     { nome: "Corumbiara" },
     { nome: "Costa Marques" },
     { nome: "Cujubim" },
     { nome: "Espigão d'Oeste" },
     { nome: "Governador Jorge Teixeira" },
     { nome: "Guajará-Mirim" },
     { nome: "Itapuã do Oeste" },
     { nome: "Jaru" },
     { nome: "Ji-Paraná" },
     { nome: "Machadinho d'Oeste" },
     { nome: "Ministro Andreazza" },
     { nome: "Mirante da Serra" },
     { nome: "Monte Negro" },
     { nome: "Nova Brasilândia d'Oeste" },
     { nome: "Nova Mamoré" },
     { nome: "Nova União" },
     { nome: "Novo Horizonte do Oeste" },
     { nome: "Ouro Preto do Oeste" },
     { nome: "Parecis" },
     { nome: "Pimenta Bueno" },
     { nome: "Pimenteiras do Oeste" },
     { nome: "Porto Velho" },
     { nome: "Presidente Médici" },
     { nome: "Primavera de Rondônia" },
     { nome: "Rio Crespo" },
     { nome: "Rolim de Moura" },
     { nome: "Santa Luzia d'Oeste" },
     { nome: "São Felipe d'Oeste" },
     { nome: "São Francisco do Guaporé" },
     { nome: "São Miguel do Guaporé" },
     { nome: "Seringueiras" },
     { nome: "Teixeirópolis" },
     { nome: "Theobroma" },
     { nome: "Urupá" },
     { nome: "Vale do Anari" },
     { nome: "Vale do Paraíso" },
     { nome: "Vilhena" }
  ]
)