RS = Estado.find_by_sigla("RS")
RS.cidades.create(
  [
   { nome: "Aceguá" },
   { nome: "Água Santa" },
   { nome: "Agudo" },
   { nome: "Ajuricaba" },
   { nome: "Alecrim" },
   { nome: "Alegrete" },
   { nome: "Alegria" },
   { nome: "Almirante Tamandaré do Sul" },
   { nome: "Alpestre" },
   { nome: "Alto Alegre" },
   { nome: "Alto Feliz" },
   { nome: "Alvorada" },
   { nome: "Amaral Ferrador" },
   { nome: "Ametista do Sul" },
   { nome: "André da Rocha" },
   { nome: "Anta Gorda" },
   { nome: "Antônio Prado" },
   { nome: "Arambaré" },
   { nome: "Araricá" },
   { nome: "Aratiba" },
   { nome: "Arroio do Meio" },
   { nome: "Arroio do Padre" },
   { nome: "Arroio do Sal" },
   { nome: "Arroio do Tigre" },
   { nome: "Arroio dos Ratos" },
   { nome: "Arroio Grande" },
   { nome: "Arvorezinha" },
   { nome: "Augusto Pestana" },
   { nome: "Áurea" },
   { nome: "Bagé" },
   { nome: "Balneário Pinhal" },
   { nome: "Barão" },
   { nome: "Barão de Cotegipe" },
   { nome: "Barão do Triunfo" },
   { nome: "Barra do Guarita" },
   { nome: "Barra do Quaraí" },
   { nome: "Barra do Ribeiro" },
   { nome: "Barra do Rio Azul" },
   { nome: "Barra Funda" },
   { nome: "Barracão" },
   { nome: "Barros Cassal" },
   { nome: "Benjamin Constan do Sul" },
   { nome: "Bento Gonçalves" },
   { nome: "Boa Vista das Missões" },
   { nome: "Boa Vista do Buricá" },
   { nome: "Boa Vista do Cadeado" },
   { nome: "Boa Vista do Incra" },
   { nome: "Boa Vista do Sul" },
   { nome: "Bom Jesus" },
   { nome: "Bom Princípio" },
   { nome: "Bom Progresso" },
   { nome: "Bom Retiro do Sul" },
   { nome: "Boqueirão do Leão" },
   { nome: "Bossoroca" },
   { nome: "Bozano" },
   { nome: "Braga" },
   { nome: "Brochier" },
   { nome: "Butiá" },
   { nome: "Caçapava do Sul" },
   { nome: "Cacequi" },
   { nome: "Cachoeira do Sul" },
   { nome: "Cachoeirinha" },
   { nome: "Cacique Doble" },
   { nome: "Caibaté" },
   { nome: "Caiçara" },
   { nome: "Camaquã" },
   { nome: "Camargo" },
   { nome: "Cambará do Sul" },
   { nome: "Campestre da Serra" },
   { nome: "Campina das Missões" },
   { nome: "Campinas do Sul" },
   { nome: "Campo Bom" },
   { nome: "Campo Novo" },
   { nome: "Campos Borges" },
   { nome: "Candelária" },
   { nome: "Cândido Godói" },
   { nome: "Candiota" },
   { nome: "Canela" },
   { nome: "Canguçu" },
   { nome: "Canoas" },
   { nome: "Canudos do Vale" },
   { nome: "Capão Bonito do Sul" },
   { nome: "Capão da Canoa" },
   { nome: "Capão do Cipó" },
   { nome: "Capão do Leão" },
   { nome: "Capela de Santana" },
   { nome: "Capitão" },
   { nome: "Capivari do Sul" },
   { nome: "Caraá" },
   { nome: "Carazinho" },
   { nome: "Carlos Barbosa" },
   { nome: "Carlos Gomes" },
   { nome: "Casca" },
   { nome: "Caseiros" },
   { nome: "Catuípe" },
   { nome: "Caxias do Sul" },
   { nome: "Centenário" },
   { nome: "Cerrito" },
   { nome: "Cerro Branco" },
   { nome: "Cerro Grande" },
   { nome: "Cerro Grande do Sul" },
   { nome: "Cerro Largo" },
   { nome: "Chapada" },
   { nome: "Charqueadas" },
   { nome: "Charrua" },
   { nome: "Chiapeta" },
   { nome: "Chuí" },
   { nome: "Chuvisca" },
   { nome: "Cidreira" },
   { nome: "Ciríaco" },
   { nome: "Colinas" },
   { nome: "Colorado" },
   { nome: "Condor" },
   { nome: "Constantina" },
   { nome: "Coqueiro Baixo" },
   { nome: "Coqueiros do Sul" },
   { nome: "Coronel Barros" },
   { nome: "Coronel Bicaco" },
   { nome: "Coronel Pilar" },
   { nome: "Cotiporã" },
   { nome: "Coxilha" },
   { nome: "Crissiumal" },
   { nome: "Cristal" },
   { nome: "Cristal do Sul" },
   { nome: "Cruz Alta" },
   { nome: "Cruzaltense" },
   { nome: "Cruzeiro do Sul" },
   { nome: "David Canabarro" },
   { nome: "Derrubadas" },
   { nome: "Dezesseis de Novembro" },
   { nome: "Dilermando de Aguiar" },
   { nome: "Dois Irmãos" },
   { nome: "Dois Irmãos das Missões" },
   { nome: "Dois Lajeados" },
   { nome: "Dom Feliciano" },
   { nome: "Dom Pedrito" },
   { nome: "Dom Pedro de Alcântara" },
   { nome: "Dona Francisca" },
   { nome: "Doutor Maurício Cardoso" },
   { nome: "Doutor Ricardo" },
   { nome: "Eldorado do Sul" },
   { nome: "Encantado" },
   { nome: "Encruzilhada do Sul" },
   { nome: "Engenho Velho" },
   { nome: "Entre Rios do Sul" },
   { nome: "Entre-Ijuís" },
   { nome: "Erebango" },
   { nome: "Erechim" },
   { nome: "Ernestina" },
   { nome: "Erval Grande" },
   { nome: "Erval Seco" },
   { nome: "Esmeralda" },
   { nome: "Esperança do Sul" },
   { nome: "Espumoso" },
   { nome: "Estação" },
   { nome: "Estância Velha" },
   { nome: "Esteio" },
   { nome: "Estrela" },
   { nome: "Estrela Velha" },
   { nome: "Eugênio de Castro" },
   { nome: "Fagundes Varela" },
   { nome: "Farroupilha" },
   { nome: "Faxinal do Soturno" },
   { nome: "Faxinalzinho" },
   { nome: "Fazenda Vilanova" },
   { nome: "Feliz" },
   { nome: "Flores da Cunha" },
   { nome: "Floriano Peixoto" },
   { nome: "Fontoura Xavier" },
   { nome: "Formigueiro" },
   { nome: "Forquetinha" },
   { nome: "Fortaleza dos Valos" },
   { nome: "Frederico Westphalen" },
   { nome: "Garibaldi" },
   { nome: "Garruchos" },
   { nome: "Gaurama" },
   { nome: "General Câmara" },
   { nome: "Gentil" },
   { nome: "Getúlio Vargas" },
   { nome: "Giruá" },
   { nome: "Glorinha" },
   { nome: "Gramado" },
   { nome: "Gramado dos Loureiros" },
   { nome: "Gramado Xavier" },
   { nome: "Gravataí" },
   { nome: "Guabiju" },
   { nome: "Guaíba" },
   { nome: "Guaporé" },
   { nome: "Guarani das Missões" },
   { nome: "Harmonia" },
   { nome: "Herval" },
   { nome: "Herveiras" },
   { nome: "Horizontina" },
   { nome: "Hulha Negra" },
   { nome: "Humaitá" },
   { nome: "Ibarama" },
   { nome: "Ibiaçá" },
   { nome: "Ibiraiaras" },
   { nome: "Ibirapuitã" },
   { nome: "Ibirubá" },
   { nome: "Igrejinha" },
   { nome: "Ijuí" },
   { nome: "Ilópolis" },
   { nome: "Imbé" },
   { nome: "Imigrante" },
   { nome: "Independência" },
   { nome: "Inhacorá" },
   { nome: "Ipê" },
   { nome: "Ipiranga do Sul" },
   { nome: "Iraí" },
   { nome: "Itaara" },
   { nome: "Itacurubi" },
   { nome: "Itapuca" },
   { nome: "Itaqui" },
   { nome: "Itati" },
   { nome: "Itatiba do Sul" },
   { nome: "Ivorá" },
   { nome: "Ivoti" },
   { nome: "Jaboticaba" },
   { nome: "Jacuizinho" },
   { nome: "Jacutinga" },
   { nome: "Jaguarão" },
   { nome: "Jaguari" },
   { nome: "Jaquirana" },
   { nome: "Jari" },
   { nome: "Jóia" },
   { nome: "Júlio de Castilhos" },
   { nome: "Lagoa Bonita do Sul" },
   { nome: "Lagoa dos Três Cantos" },
   { nome: "Lagoa Vermelha" },
   { nome: "Lagoão" },
   { nome: "Lajeado" },
   { nome: "Lajeado do Bugre" },
   { nome: "Lavras do Sul" },
   { nome: "Liberato Salzano" },
   { nome: "Lindolfo Collor" },
   { nome: "Linha Nova" },
   { nome: "Maçambara" },
   { nome: "Machadinho" },
   { nome: "Mampituba" },
   { nome: "Manoel Viana" },
   { nome: "Maquiné" },
   { nome: "Maratá" },
   { nome: "Marau" },
   { nome: "Marcelino Ramos" },
   { nome: "Mariana Pimentel" },
   { nome: "Mariano Moro" },
   { nome: "Marques de Souza" },
   { nome: "Mata" },
   { nome: "Mato Castelhano" },
   { nome: "Mato Leitão" },
   { nome: "Mato Queimado" },
   { nome: "Maximiliano de Almeida" },
   { nome: "Minas do Leão" },
   { nome: "Miraguaí" },
   { nome: "Montauri" },
   { nome: "Monte Alegre dos Campos" },
   { nome: "Monte Belo do Sul" },
   { nome: "Montenegro" },
   { nome: "Mormaço" },
   { nome: "Morrinhos do Sul" },
   { nome: "Morro Redondo" },
   { nome: "Morro Reuter" },
   { nome: "Mostardas" },
   { nome: "Muçum" },
   { nome: "Muitos Capões" },
   { nome: "Muliterno" },
   { nome: "Não-Me-Toque" },
   { nome: "Nicolau Vergueiro" },
   { nome: "Nonoai" },
   { nome: "Nova Alvorada" },
   { nome: "Nova Araçá" },
   { nome: "Nova Bassano" },
   { nome: "Nova Boa Vista" },
   { nome: "Nova Bréscia" },
   { nome: "Nova Candelária" },
   { nome: "Nova Esperança do Sul" },
   { nome: "Nova Hartz" },
   { nome: "Nova Pádua" },
   { nome: "Nova Palma" },
   { nome: "Nova Petrópolis" },
   { nome: "Nova Prata" },
   { nome: "Nova Ramada" },
   { nome: "Nova Roma do Sul" },
   { nome: "Nova Santa Rita" },
   { nome: "Novo Barreiro" },
   { nome: "Novo Cabrais" },
   { nome: "Novo Hamburgo" },
   { nome: "Novo Machado" },
   { nome: "Novo Tiradentes" },
   { nome: "Novo Xingu" },
   { nome: "Osório" },
   { nome: "Paim Filho" },
   { nome: "Palmares do Sul" },
   { nome: "Palmeira das Missões" },
   { nome: "Palmitinho" },
   { nome: "Panambi" },
   { nome: "Pântano Grande" },
   { nome: "Paraí" },
   { nome: "Paraíso do Sul" },
   { nome: "Pareci Novo" },
   { nome: "Parobé" },
   { nome: "Passa Sete" },
   { nome: "Passo do Sobrado" },
   { nome: "Passo Fundo" },
   { nome: "Paulo Bento" },
   { nome: "Paverama" },
   { nome: "Pedras Altas" },
   { nome: "Pedro Osório" },
   { nome: "Pejuçara" },
   { nome: "Pelotas" },
   { nome: "Picada Café" },
   { nome: "Pinhal" },
   { nome: "Pinhal da Serra" },
   { nome: "Pinhal Grande" },
   { nome: "Pinheirinho do Vale" },
   { nome: "Pinheiro Machado" },
   { nome: "Pirapó" },
   { nome: "Piratini" },
   { nome: "Planalto" },
   { nome: "Poço das Antas" },
   { nome: "Pontão" },
   { nome: "Ponte Preta" },
   { nome: "Portão" },
   { nome: "Porto Alegre" },
   { nome: "Porto Lucena" },
   { nome: "Porto Mauá" },
   { nome: "Porto Vera Cruz" },
   { nome: "Porto Xavier" },
   { nome: "Pouso Novo" },
   { nome: "Presidente Lucena" },
   { nome: "Progresso" },
   { nome: "Protásio Alves" },
   { nome: "Putinga" },
   { nome: "Quaraí" },
   { nome: "Quatro Irmãos" },
   { nome: "Quevedos" },
   { nome: "Quinze de Novembro" },
   { nome: "Redentora" },
   { nome: "Relvado" },
   { nome: "Restinga Seca" },
   { nome: "Rio dos Índios" },
   { nome: "Rio Grande" },
   { nome: "Rio Pardo" },
   { nome: "Riozinho" },
   { nome: "Roca Sales" },
   { nome: "Rodeio Bonito" },
   { nome: "Rolador" },
   { nome: "Rolante" },
   { nome: "Ronda Alta" },
   { nome: "Rondinha" },
   { nome: "Roque Gonzales" },
   { nome: "Rosário do Sul" },
   { nome: "Sagrada Família" },
   { nome: "Saldanha Marinho" },
   { nome: "Salto do Jacuí" },
   { nome: "Salvador das Missões" },
   { nome: "Salvador do Sul" },
   { nome: "Sananduva" },
   { nome: "Santa Bárbara do Sul" },
   { nome: "Santa Cecília do Sul" },
   { nome: "Santa Clara do Sul" },
   { nome: "Santa Cruz do Sul" },
   { nome: "Santa Margarida do Sul" },
   { nome: "Santa Maria" },
   { nome: "Santa Maria do Herval" },
   { nome: "Santa Rosa" },
   { nome: "Santa Tereza" },
   { nome: "Santa Vitória do Palmar" },
   { nome: "Santana da Boa Vista" },
   { nome: "Santana do Livramento" },
   { nome: "Santiago" },
   { nome: "Santo Ângelo" },
   { nome: "Santo Antônio da Patrulha" },
   { nome: "Santo Antônio das Missões" },
   { nome: "Santo Antônio do Palma" },
   { nome: "Santo Antônio do Planalto" },
   { nome: "Santo Augusto" },
   { nome: "Santo Cristo" },
   { nome: "Santo Expedito do Sul" },
   { nome: "São Borja" },
   { nome: "São Domingos do Sul" },
   { nome: "São Francisco de Assis" },
   { nome: "São Francisco de Paula" },
   { nome: "São Gabriel" },
   { nome: "São Jerônimo" },
   { nome: "São João da Urtiga" },
   { nome: "São João do Polêsine" },
   { nome: "São Jorge" },
   { nome: "São José das Missões" },
   { nome: "São José do Herval" },
   { nome: "São José do Hortêncio" },
   { nome: "São José do Inhacorá" },
   { nome: "São José do Norte" },
   { nome: "São José do Ouro" },
   { nome: "São José do Sul" },
   { nome: "São José dos Ausentes" },
   { nome: "São Leopoldo" },
   { nome: "São Lourenço do Sul" },
   { nome: "São Luiz Gonzaga" },
   { nome: "São Marcos" },
   { nome: "São Martinho" },
   { nome: "São Martinho da Serra" },
   { nome: "São Miguel das Missões" },
   { nome: "São Nicolau" },
   { nome: "São Paulo das Missões" },
   { nome: "São Pedro da Serra" },
   { nome: "São Pedro das Missões" },
   { nome: "São Pedro do Butiá" },
   { nome: "São Pedro do Sul" },
   { nome: "São Sebastião do Caí" },
   { nome: "São Sepé" },
   { nome: "São Valentim" },
   { nome: "São Valentim do Sul" },
   { nome: "São Valério do Sul" },
   { nome: "São Vendelino" },
   { nome: "São Vicente do Sul" },
   { nome: "Sapiranga" },
   { nome: "Sapucaia do Sul" },
   { nome: "Sarandi" },
   { nome: "Seberi" },
   { nome: "Sede Nova" },
   { nome: "Segredo" },
   { nome: "Selbach" },
   { nome: "Senador Salgado Filho" },
   { nome: "Sentinela do Sul" },
   { nome: "Serafina Corrêa" },
   { nome: "Sério" },
   { nome: "Sertão" },
   { nome: "Sertão Santana" },
   { nome: "Sete de Setembro" },
   { nome: "Severiano de Almeida" },
   { nome: "Silveira Martins" },
   { nome: "Sinimbu" },
   { nome: "Sobradinho" },
   { nome: "Soledade" },
   { nome: "Tabaí" },
   { nome: "Tapejara" },
   { nome: "Tapera" },
   { nome: "Tapes" },
   { nome: "Taquara" },
   { nome: "Taquari" },
   { nome: "Taquaruçu do Sul" },
   { nome: "Tavares" },
   { nome: "Tenente Portela" },
   { nome: "Terra de Areia" },
   { nome: "Teutônia" },
   { nome: "Tio Hugo" },
   { nome: "Tiradentes do Sul" },
   { nome: "Toropi" },
   { nome: "Torres" },
   { nome: "Tramandaí" },
   { nome: "Travesseiro" },
   { nome: "Três Arroios" },
   { nome: "Três Cachoeiras" },
   { nome: "Três Coroas" },
   { nome: "Três de Maio" },
   { nome: "Três Forquilhas" },
   { nome: "Três Palmeiras" },
   { nome: "Três Passos" },
   { nome: "Trindade do Sul" },
   { nome: "Triunfo" },
   { nome: "Tucunduva" },
   { nome: "Tunas" },
   { nome: "Tupanci do Sul" },
   { nome: "Tupanciretã" },
   { nome: "Tupandi" },
   { nome: "Tuparendi" },
   { nome: "Turuçu" },
   { nome: "Ubiretama" },
   { nome: "União da Serra" },
   { nome: "Unistalda" },
   { nome: "Uruguaiana" },
   { nome: "Vacaria" },
   { nome: "Vale do Sol" },
   { nome: "Vale Real" },
   { nome: "Vale Verde" },
   { nome: "Vanini" },
   { nome: "Venâncio Aires" },
   { nome: "Vera Cruz" },
   { nome: "Veranópolis" },
   { nome: "Vespasiano Correa" },
   { nome: "Viadutos" },
   { nome: "Viamão" },
   { nome: "Vicente Dutra" },
   { nome: "Victor Graeff" },
   { nome: "Vila Flores" },
   { nome: "Vila Lângaro" },
   { nome: "Vila Maria" },
   { nome: "Vila Nova do Sul" },
   { nome: "Vista Alegre" },
   { nome: "Vista Alegre do Prata" },
   { nome: "Vista Gaúcha" },
   { nome: "Vitória das Missões" },
   { nome: "Westfália" },
   { nome: "Xangri-lá" }
  ]
)