SC = Estado.find_by_sigla("SC")
SC.cidades.create(
  [
   { nome: "Abdon Batista" },
   { nome: "Abelardo Luz" },
   { nome: "Agrolândia" },
   { nome: "Agronômica" },
   { nome: "Água Doce" },
   { nome: "Águas de Chapecó" },
   { nome: "Águas Frias" },
   { nome: "Águas Mornas" },
   { nome: "Alfredo Wagner" },
   { nome: "Alto Bela Vista" },
   { nome: "Anchieta" },
   { nome: "Angelina" },
   { nome: "Anita Garibaldi" },
   { nome: "Anitápolis" },
   { nome: "Antônio Carlos" },
   { nome: "Apiúna" },
   { nome: "Arabutã" },
   { nome: "Araquari" },
   { nome: "Araranguá" },
   { nome: "Armazém" },
   { nome: "Arroio Trinta" },
   { nome: "Arvoredo" },
   { nome: "Ascurra" },
   { nome: "Atalanta" },
   { nome: "Aurora" },
   { nome: "Balneário Arroio do Silva" },
   { nome: "Balneário Barra do Sul" },
   { nome: "Balneário Camboriú" },
   { nome: "Balneário Gaivota" },
   { nome: "Bandeirante" },
   { nome: "Barra Bonita" },
   { nome: "Barra Velha" },
   { nome: "Bela Vista do Toldo" },
   { nome: "Belmonte" },
   { nome: "Benedito Novo" },
   { nome: "Biguaçu" },
   { nome: "Blumenau" },
   { nome: "Bocaina do Sul" },
   { nome: "Bom Jardim da Serra" },
   { nome: "Bom Jesus" },
   { nome: "Bom Jesus do Oeste" },
   { nome: "Bom Retiro" },
   { nome: "Bombinhas" },
   { nome: "Botuverá" },
   { nome: "Braço do Norte" },
   { nome: "Braço do Trombudo" },
   { nome: "Brunópolis" },
   { nome: "Brusque" },
   { nome: "Caçador" },
   { nome: "Caibi" },
   { nome: "Calmon" },
   { nome: "Camboriú" },
   { nome: "Campo Alegre" },
   { nome: "Campo Belo do Sul" },
   { nome: "Campo Erê" },
   { nome: "Campos Novos" },
   { nome: "Canelinha" },
   { nome: "Canoinhas" },
   { nome: "Capão Alto" },
   { nome: "Capinzal" },
   { nome: "Capivari de Baixo" },
   { nome: "Catanduvas" },
   { nome: "Caxambu do Sul" },
   { nome: "Celso Ramos" },
   { nome: "Cerro Negro" },
   { nome: "Chapadão do Lageado" },
   { nome: "Chapecó" },
   { nome: "Cocal do Sul" },
   { nome: "Concórdia" },
   { nome: "Cordilheira Alta" },
   { nome: "Coronel Freitas" },
   { nome: "Coronel Martins" },
   { nome: "Correia Pinto" },
   { nome: "Corupá" },
   { nome: "Criciúma" },
   { nome: "Cunha Porã" },
   { nome: "Cunhataí" },
   { nome: "Curitibanos" },
   { nome: "Descanso" },
   { nome: "Dionísio Cerqueira" },
   { nome: "Dona Emma" },
   { nome: "Doutor Pedrinho" },
   { nome: "Entre Rios" },
   { nome: "Ermo" },
   { nome: "Erval Velho" },
   { nome: "Faxinal dos Guedes" },
   { nome: "Flor do Sertão" },
   { nome: "Florianópolis" },
   { nome: "Formosa do Sul" },
   { nome: "Forquilhinha" },
   { nome: "Fraiburgo" },
   { nome: "Frei Rogério" },
   { nome: "Galvão" },
   { nome: "Garopaba" },
   { nome: "Garuva" },
   { nome: "Gaspar" },
   { nome: "Governador Celso Ramos" },
   { nome: "Grão Pará" },
   { nome: "Gravatal" },
   { nome: "Guabiruba" },
   { nome: "Guaraciaba" },
   { nome: "Guaramirim" },
   { nome: "Guarujá do Sul" },
   { nome: "Guatambú" },
   { nome: "Herval d'Oeste" },
   { nome: "Ibiam" },
   { nome: "Ibicaré" },
   { nome: "Ibirama" },
   { nome: "Içara" },
   { nome: "Ilhota" },
   { nome: "Imaruí" },
   { nome: "Imbituba" },
   { nome: "Imbuia" },
   { nome: "Indaial" },
   { nome: "Iomerê" },
   { nome: "Ipira" },
   { nome: "Iporã do Oeste" },
   { nome: "Ipuaçu" },
   { nome: "Ipumirim" },
   { nome: "Iraceminha" },
   { nome: "Irani" },
   { nome: "Irati" },
   { nome: "Irineópolis" },
   { nome: "Itá" },
   { nome: "Itaiópolis" },
   { nome: "Itajaí" },
   { nome: "Itapema" },
   { nome: "Itapiranga" },
   { nome: "Itapoá" },
   { nome: "Ituporanga" },
   { nome: "Jaborá" },
   { nome: "Jacinto Machado" },
   { nome: "Jaguaruna" },
   { nome: "Jaraguá do Sul" },
   { nome: "Jardinópolis" },
   { nome: "Joaçaba" },
   { nome: "Joinville" },
   { nome: "José Boiteux" },
   { nome: "Jupiá" },
   { nome: "Lacerdópolis" },
   { nome: "Lages" },
   { nome: "Laguna" },
   { nome: "Lajeado Grande" },
   { nome: "Laurentino" },
   { nome: "Lauro Muller" },
   { nome: "Lebon Régis" },
   { nome: "Leoberto Leal" },
   { nome: "Lindóia do Sul" },
   { nome: "Lontras" },
   { nome: "Luiz Alves" },
   { nome: "Luzerna" },
   { nome: "Macieira" },
   { nome: "Mafra" },
   { nome: "Major Gercino" },
   { nome: "Major Vieira" },
   { nome: "Maracajá" },
   { nome: "Maravilha" },
   { nome: "Marema" },
   { nome: "Massaranduba" },
   { nome: "Matos Costa" },
   { nome: "Meleiro" },
   { nome: "Mirim Doce" },
   { nome: "Modelo" },
   { nome: "Mondaí" },
   { nome: "Monte Carlo" },
   { nome: "Monte Castelo" },
   { nome: "Morro da Fumaça" },
   { nome: "Morro Grande" },
   { nome: "Navegantes" },
   { nome: "Nova Erechim" },
   { nome: "Nova Itaberaba" },
   { nome: "Nova Trento" },
   { nome: "Nova Veneza" },
   { nome: "Novo Horizonte" },
   { nome: "Orleans" },
   { nome: "Otacílio Costa" },
   { nome: "Ouro" },
   { nome: "Ouro Verde" },
   { nome: "Paial" },
   { nome: "Painel" },
   { nome: "Palhoça" },
   { nome: "Palma Sola" },
   { nome: "Palmeira" },
   { nome: "Palmitos" },
   { nome: "Papanduva" },
   { nome: "Paraíso" },
   { nome: "Passo de Torres" },
   { nome: "Passos Maia" },
   { nome: "Paulo Lopes" },
   { nome: "Pedras Grandes" },
   { nome: "Penha" },
   { nome: "Peritiba" },
   { nome: "Petrolândia" },
   { nome: "Piçarras" },
   { nome: "Pinhalzinho" },
   { nome: "Pinheiro Preto" },
   { nome: "Piratuba" },
   { nome: "Planalto Alegre" },
   { nome: "Pomerode" },
   { nome: "Ponte Alta" },
   { nome: "Ponte Alta do Norte" },
   { nome: "Ponte Serrada" },
   { nome: "Porto Belo" },
   { nome: "Porto União" },
   { nome: "Pouso Redondo" },
   { nome: "Praia Grande" },
   { nome: "Presidente Castelo Branco" },
   { nome: "Presidente Getúlio" },
   { nome: "Presidente Nereu" },
   { nome: "Princesa" },
   { nome: "Quilombo" },
   { nome: "Rancho Queimado" },
   { nome: "Rio das Antas" },
   { nome: "Rio do Campo" },
   { nome: "Rio do Oeste" },
   { nome: "Rio do Sul" },
   { nome: "Rio dos Cedros" },
   { nome: "Rio Fortuna" },
   { nome: "Rio Negrinho" },
   { nome: "Rio Rufino" },
   { nome: "Riqueza" },
   { nome: "Rodeio" },
   { nome: "Romelândia" },
   { nome: "Salete" },
   { nome: "Saltinho" },
   { nome: "Salto Veloso" },
   { nome: "Sangão" },
   { nome: "Santa Cecília" },
   { nome: "Santa Helena" },
   { nome: "Santa Rosa de Lima" },
   { nome: "Santa Rosa do Sul" },
   { nome: "Santa Terezinha" },
   { nome: "Santa Terezinha do Progresso" },
   { nome: "Santiago do Sul" },
   { nome: "Santo Amaro da Imperatriz" },
   { nome: "São Bento do Sul" },
   { nome: "São Bernardino" },
   { nome: "São Bonifácio" },
   { nome: "São Carlos" },
   { nome: "São Cristovão do Sul" },
   { nome: "São Domingos" },
   { nome: "São Francisco do Sul" },
   { nome: "São João Batista" },
   { nome: "São João do Itaperiú" },
   { nome: "São João do Oeste" },
   { nome: "São João do Sul" },
   { nome: "São Joaquim" },
   { nome: "São José" },
   { nome: "São José do Cedro" },
   { nome: "São José do Cerrito" },
   { nome: "São Lourenço do Oeste" },
   { nome: "São Ludgero" },
   { nome: "São Martinho" },
   { nome: "São Miguel da Boa Vista" },
   { nome: "São Miguel do Oeste" },
   { nome: "São Pedro de Alcântara" },
   { nome: "Saudades" },
   { nome: "Schroeder" },
   { nome: "Seara" },
   { nome: "Serra Alta" },
   { nome: "Siderópolis" },
   { nome: "Sombrio" },
   { nome: "Sul Brasil" },
   { nome: "Taió" },
   { nome: "Tangará" },
   { nome: "Tigrinhos" },
   { nome: "Tijucas" },
   { nome: "Timbé do Sul" },
   { nome: "Timbó" },
   { nome: "Timbó Grande" },
   { nome: "Três Barras" },
   { nome: "Treviso" },
   { nome: "Treze de Maio" },
   { nome: "Treze Tílias" },
   { nome: "Trombudo Central" },
   { nome: "Tubarão" },
   { nome: "Tunápolis" },
   { nome: "Turvo" },
   { nome: "União do Oeste" },
   { nome: "Urubici" },
   { nome: "Urupema" },
   { nome: "Urussanga" },
   { nome: "Vargeão" },
   { nome: "Vargem" },
   { nome: "Vargem Bonita" },
   { nome: "Vidal Ramos" },
   { nome: "Videira" },
   { nome: "Vitor Meireles" },
   { nome: "Witmarsum" },
   { nome: "Xanxerê" },
   { nome: "Xavantina" },
   { nome: "Xaxim" },
   { nome: "Zortéa" }
  ]
)