SP = Estado.find_by_sigla("SP")
SP.cidades.create(
  [
   { nome: "Adamantina" },
   { nome: "Adolfo" },
   { nome: "Aguaí" },
   { nome: "Águas da Prata" },
   { nome: "Águas de Lindóia" },
   { nome: "Águas de Santa Bárbara" },
   { nome: "Águas de São Pedro" },
   { nome: "Agudos" },
   { nome: "Alambari" },
   { nome: "Alfredo Marcondes" },
   { nome: "Altair" },
   { nome: "Altinópolis" },
   { nome: "Alto Alegre" },
   { nome: "Alumínio" },
   { nome: "Álvares Florence" },
   { nome: "Álvares Machado" },
   { nome: "Álvaro de Carvalho" },
   { nome: "Alvinlândia" },
   { nome: "Americana" },
   { nome: "Américo Brasiliense" },
   { nome: "Américo de Campos" },
   { nome: "Amparo" },
   { nome: "Analândia" },
   { nome: "Andradina" },
   { nome: "Angatuba" },
   { nome: "Anhembi" },
   { nome: "Anhumas" },
   { nome: "Aparecida" },
   { nome: "Aparecida d'Oeste" },
   { nome: "Apiaí" },
   { nome: "Araçariguama" },
   { nome: "Araçatuba" },
   { nome: "Araçoiaba da Serra" },
   { nome: "Aramina" },
   { nome: "Arandu" },
   { nome: "Arapeí" },
   { nome: "Araraquara" },
   { nome: "Araras" },
   { nome: "Arco-Íris" },
   { nome: "Arealva" },
   { nome: "Areias" },
   { nome: "Areiópolis" },
   { nome: "Ariranha" },
   { nome: "Artur Nogueira" },
   { nome: "Arujá" },
   { nome: "Aspásia" },
   { nome: "Assis" },
   { nome: "Atibaia" },
   { nome: "Auriflama" },
   { nome: "Avaí" },
   { nome: "Avanhandava" },
   { nome: "Avaré" },
   { nome: "Bady Bassitt" },
   { nome: "Balbinos" },
   { nome: "Bálsamo" },
   { nome: "Bananal" },
   { nome: "Barão de Antonina" },
   { nome: "Barbosa" },
   { nome: "Bariri" },
   { nome: "Barra Bonita" },
   { nome: "Barra do Chapéu" },
   { nome: "Barra do Turvo" },
   { nome: "Barretos" },
   { nome: "Barrinha" },
   { nome: "Barueri" },
   { nome: "Bastos" },
   { nome: "Batatais" },
   { nome: "Bauru" },
   { nome: "Bebedouro" },
   { nome: "Bento de Abreu" },
   { nome: "Bernardino de Campos" },
   { nome: "Bertioga" },
   { nome: "Bilac" },
   { nome: "Birigui" },
   { nome: "Biritiba-Mirim" },
   { nome: "Boa Esperança do Sul" },
   { nome: "Bocaina" },
   { nome: "Bofete" },
   { nome: "Boituva" },
   { nome: "Bom Jesus dos Perdões" },
   { nome: "Bom Sucesso de Itararé" },
   { nome: "Borá" },
   { nome: "Boracéia" },
   { nome: "Borborema" },
   { nome: "Borebi" },
   { nome: "Botucatu" },
   { nome: "Bragança Paulista" },
   { nome: "Braúna" },
   { nome: "Brejo Alegre" },
   { nome: "Brodowski" },
   { nome: "Brotas" },
   { nome: "Buri" },
   { nome: "Buritama" },
   { nome: "Buritizal" },
   { nome: "Cabrália Paulista" },
   { nome: "Cabreúva" },
   { nome: "Caçapava" },
   { nome: "Cachoeira Paulista" },
   { nome: "Caconde" },
   { nome: "Cafelândia" },
   { nome: "Caiabu" },
   { nome: "Caieiras" },
   { nome: "Caiuá" },
   { nome: "Cajamar" },
   { nome: "Cajati" },
   { nome: "Cajobi" },
   { nome: "Cajuru" },
   { nome: "Campina do Monte Alegre" },
   { nome: "Campinas" },
   { nome: "Campo Limpo Paulista" },
   { nome: "Campos do Jordão" },
   { nome: "Campos Novos Paulista" },
   { nome: "Cananéia" },
   { nome: "Canas" },
   { nome: "Cândido Mota" },
   { nome: "Cândido Rodrigues" },
   { nome: "Canitar" },
   { nome: "Capão Bonito" },
   { nome: "Capela do Alto" },
   { nome: "Capivari" },
   { nome: "Caraguatatuba" },
   { nome: "Carapicuíba" },
   { nome: "Cardoso" },
   { nome: "Casa Branca" },
   { nome: "Cássia dos Coqueiros" },
   { nome: "Castilho" },
   { nome: "Catanduva" },
   { nome: "Catiguá" },
   { nome: "Cedral" },
   { nome: "Cerqueira César" },
   { nome: "Cerquilho" },
   { nome: "Cesário Lange" },
   { nome: "Charqueada" },
   { nome: "Chavantes" },
   { nome: "Clementina" },
   { nome: "Colina" },
   { nome: "Colômbia" },
   { nome: "Conchal" },
   { nome: "Conchas" },
   { nome: "Cordeirópolis" },
   { nome: "Coroados" },
   { nome: "Coronel Macedo" },
   { nome: "Corumbataí" },
   { nome: "Cosmópolis" },
   { nome: "Cosmorama" },
   { nome: "Cotia" },
   { nome: "Cravinhos" },
   { nome: "Cristais Paulista" },
   { nome: "Cruzália" },
   { nome: "Cruzeiro" },
   { nome: "Cubatão" },
   { nome: "Cunha" },
   { nome: "Descalvado" },
   { nome: "Diadema" },
   { nome: "Dirce Reis" },
   { nome: "Divinolândia" },
   { nome: "Dobrada" },
   { nome: "Dois Córregos" },
   { nome: "Dolcinópolis" },
   { nome: "Dourado" },
   { nome: "Dracena" },
   { nome: "Duartina" },
   { nome: "Dumont" },
   { nome: "Echaporã" },
   { nome: "Eldorado" },
   { nome: "Elias Fausto" },
   { nome: "Elisiário" },
   { nome: "Embaúba" },
   { nome: "Embu" },
   { nome: "Embu-Guaçu" },
   { nome: "Emilianópolis" },
   { nome: "Engenheiro Coelho" },
   { nome: "Espírito Santo do Pinhal" },
   { nome: "Espírito Santo do Turvo" },
   { nome: "Estiva Gerbi" },
   { nome: "Estrela d'Oeste" },
   { nome: "Estrela do Norte" },
   { nome: "Euclides da Cunha Paulista" },
   { nome: "Fartura" },
   { nome: "Fernando Prestes" },
   { nome: "Fernandópolis" },
   { nome: "Fernão" },
   { nome: "Ferraz de Vasconcelos" },
   { nome: "Flora Rica" },
   { nome: "Floreal" },
   { nome: "Florínia" },
   { nome: "Flórida Paulista" },
   { nome: "Franca" },
   { nome: "Francisco Morato" },
   { nome: "Franco da Rocha" },
   { nome: "Gabriel Monteiro" },
   { nome: "Gália" },
   { nome: "Garça" },
   { nome: "Gastão Vidigal" },
   { nome: "Gavião Peixoto" },
   { nome: "General Salgado" },
   { nome: "Getulina" },
   { nome: "Glicério" },
   { nome: "Guaiçara" },
   { nome: "Guaimbê" },
   { nome: "Guaíra" },
   { nome: "Guapiaçu" },
   { nome: "Guapiara" },
   { nome: "Guará" },
   { nome: "Guaraçaí" },
   { nome: "Guaraci" },
   { nome: "Guarani d'Oeste" },
   { nome: "Guarantã" },
   { nome: "Guararapes" },
   { nome: "Guararema" },
   { nome: "Guaratinguetá" },
   { nome: "Guareí" },
   { nome: "Guariba" },
   { nome: "Guarujá" },
   { nome: "Guarulhos" },
   { nome: "Guatapará" },
   { nome: "Guzolândia" },
   { nome: "Herculândia" },
   { nome: "Holambra" },
   { nome: "Hortolândia" },
   { nome: "Iacanga" },
   { nome: "Iacri" },
   { nome: "Iaras" },
   { nome: "Ibaté" },
   { nome: "Ibirá" },
   { nome: "Ibirarema" },
   { nome: "Ibitinga" },
   { nome: "Ibiúna" },
   { nome: "Icém" },
   { nome: "Iepê" },
   { nome: "Igaraçu do Tietê" },
   { nome: "Igarapava" },
   { nome: "Igaratá" },
   { nome: "Iguape" },
   { nome: "Ilha Comprida" },
   { nome: "Ilha Solteira" },
   { nome: "Ilhabela" },
   { nome: "Indaiatuba" },
   { nome: "Indiana" },
   { nome: "Indiaporã" },
   { nome: "Inúbia Paulista" },
   { nome: "Ipauçu" },
   { nome: "Iperó" },
   { nome: "Ipeúna" },
   { nome: "Ipiguá" },
   { nome: "Iporanga" },
   { nome: "Ipuã" },
   { nome: "Iracemápolis" },
   { nome: "Irapuã" },
   { nome: "Irapuru" },
   { nome: "Itaberá" },
   { nome: "Itaí" },
   { nome: "Itajobi" },
   { nome: "Itaju" },
   { nome: "Itanhaém" },
   { nome: "Itaóca" },
   { nome: "Itapecerica da Serra" },
   { nome: "Itapetininga" },
   { nome: "Itapeva" },
   { nome: "Itapevi" },
   { nome: "Itapira" },
   { nome: "Itapirapuã Paulista" },
   { nome: "Itápolis" },
   { nome: "Itaporanga" },
   { nome: "Itapuí" },
   { nome: "Itapura" },
   { nome: "Itaquaquecetuba" },
   { nome: "Itararé" },
   { nome: "Itariri" },
   { nome: "Itatiba" },
   { nome: "Itatinga" },
   { nome: "Itirapina" },
   { nome: "Itirapuã" },
   { nome: "Itobi" },
   { nome: "Itu" },
   { nome: "Itupeva" },
   { nome: "Ituverava" },
   { nome: "Jaborandi" },
   { nome: "Jaboticabal" },
   { nome: "Jacareí" },
   { nome: "Jaci" },
   { nome: "Jacupiranga" },
   { nome: "Jaguariúna" },
   { nome: "Jales" },
   { nome: "Jambeiro" },
   { nome: "Jandira" },
   { nome: "Jardinópolis" },
   { nome: "Jarinu" },
   { nome: "Jaú" },
   { nome: "Jeriquara" },
   { nome: "Joanópolis" },
   { nome: "João Ramalho" },
   { nome: "José Bonifácio" },
   { nome: "Júlio Mesquita" },
   { nome: "Jumirim" },
   { nome: "Jundiaí" },
   { nome: "Junqueirópolis" },
   { nome: "Juquiá" },
   { nome: "Juquitiba" },
   { nome: "Lagoinha" },
   { nome: "Laranjal Paulista" },
   { nome: "Lavínia" },
   { nome: "Lavrinhas" },
   { nome: "Leme" },
   { nome: "Lençóis Paulista" },
   { nome: "Limeira" },
   { nome: "Lindóia" },
   { nome: "Lins" },
   { nome: "Lorena" },
   { nome: "Lourdes" },
   { nome: "Louveira" },
   { nome: "Lucélia" },
   { nome: "Lucianópolis" },
   { nome: "Luís Antônio" },
   { nome: "Luiziânia" },
   { nome: "Lupércio" },
   { nome: "Lutécia" },
   { nome: "Macatuba" },
   { nome: "Macaubal" },
   { nome: "Macedônia" },
   { nome: "Magda" },
   { nome: "Mairinque" },
   { nome: "Mairiporã" },
   { nome: "Manduri" },
   { nome: "Marabá Paulista" },
   { nome: "Maracaí" },
   { nome: "Marapoama" },
   { nome: "Mariápolis" },
   { nome: "Marília" },
   { nome: "Marinópolis" },
   { nome: "Martinópolis" },
   { nome: "Matão" },
   { nome: "Mauá" },
   { nome: "Mendonça" },
   { nome: "Meridiano" },
   { nome: "Mesópolis" },
   { nome: "Miguelópolis" },
   { nome: "Mineiros do Tietê" },
   { nome: "Mira Estrela" },
   { nome: "Miracatu" },
   { nome: "Mirandópolis" },
   { nome: "Mirante do Paranapanema" },
   { nome: "Mirassol" },
   { nome: "Mirassolândia" },
   { nome: "Mococa" },
   { nome: "Mogi das Cruzes" },
   { nome: "Mogi-Guaçu" },
   { nome: "Mogi-Mirim" },
   { nome: "Mombuca" },
   { nome: "Monções" },
   { nome: "Mongaguá" },
   { nome: "Monte Alegre do Sul" },
   { nome: "Monte Alto" },
   { nome: "Monte Aprazível" },
   { nome: "Monte Azul Paulista" },
   { nome: "Monte Castelo" },
   { nome: "Monte Mor" },
   { nome: "Monteiro Lobato" },
   { nome: "Morro Agudo" },
   { nome: "Morungaba" },
   { nome: "Motuca" },
   { nome: "Murutinga do Sul" },
   { nome: "Nantes" },
   { nome: "Narandiba" },
   { nome: "Natividade da Serra" },
   { nome: "Nazaré Paulista" },
   { nome: "Neves Paulista" },
   { nome: "Nhandeara" },
   { nome: "Nipoã" },
   { nome: "Nova Aliança" },
   { nome: "Nova Campina" },
   { nome: "Nova Canaã Paulista" },
   { nome: "Nova Castilho" },
   { nome: "Nova Europa" },
   { nome: "Nova Granada" },
   { nome: "Nova Guataporanga" },
   { nome: "Nova Independência" },
   { nome: "Nova Luzitânia" },
   { nome: "Nova Odessa" },
   { nome: "Novais" },
   { nome: "Novo Horizonte" },
   { nome: "Nuporanga" },
   { nome: "Ocauçu" },
   { nome: "Óleo" },
   { nome: "Olímpia" },
   { nome: "Onda Verde" },
   { nome: "Oriente" },
   { nome: "Orindiúva" },
   { nome: "Orlândia" },
   { nome: "Osasco" },
   { nome: "Oscar Bressane" },
   { nome: "Osvaldo Cruz" },
   { nome: "Ourinhos" },
   { nome: "Ouro Verde" },
   { nome: "Ouroeste" },
   { nome: "Pacaembu" },
   { nome: "Palestina" },
   { nome: "Palmares Paulista" },
   { nome: "Palmeira d'Oeste" },
   { nome: "Palmital" },
   { nome: "Panorama" },
   { nome: "Paraguaçu Paulista" },
   { nome: "Paraibuna" },
   { nome: "Paraíso" },
   { nome: "Paranapanema" },
   { nome: "Paranapuã" },
   { nome: "Parapuã" },
   { nome: "Pardinho" },
   { nome: "Pariquera-Açu" },
   { nome: "Parisi" },
   { nome: "Patrocínio Paulista" },
   { nome: "Paulicéia" },
   { nome: "Paulínia" },
   { nome: "Paulistânia" },
   { nome: "Paulo de Faria" },
   { nome: "Pederneiras" },
   { nome: "Pedra Bela" },
   { nome: "Pedranópolis" },
   { nome: "Pedregulho" },
   { nome: "Pedreira" },
   { nome: "Pedrinhas Paulista" },
   { nome: "Pedro de Toledo" },
   { nome: "Penápolis" },
   { nome: "Pereira Barreto" },
   { nome: "Pereiras" },
   { nome: "Peruíbe" },
   { nome: "Piacatu" },
   { nome: "Piedade" },
   { nome: "Pilar do Sul" },
   { nome: "Pindamonhangaba" },
   { nome: "Pindorama" },
   { nome: "Pinhalzinho" },
   { nome: "Piquerobi" },
   { nome: "Piquete" },
   { nome: "Piracaia" },
   { nome: "Piracicaba" },
   { nome: "Piraju" },
   { nome: "Pirajuí" },
   { nome: "Pirangi" },
   { nome: "Pirapora do Bom Jesus" },
   { nome: "Pirapozinho" },
   { nome: "Pirassununga" },
   { nome: "Piratininga" },
   { nome: "Pitangueiras" },
   { nome: "Planalto" },
   { nome: "Platina" },
   { nome: "Poá" },
   { nome: "Poloni" },
   { nome: "Pompéia" },
   { nome: "Pongaí" },
   { nome: "Pontal" },
   { nome: "Pontalinda" },
   { nome: "Pontes Gestal" },
   { nome: "Populina" },
   { nome: "Porangaba" },
   { nome: "Porto Feliz" },
   { nome: "Porto Ferreira" },
   { nome: "Potim" },
   { nome: "Potirendaba" },
   { nome: "Pracinha" },
   { nome: "Pradópolis" },
   { nome: "Praia Grande" },
   { nome: "Pratânia" },
   { nome: "Presidente Alves" },
   { nome: "Presidente Bernardes" },
   { nome: "Presidente Epitácio" },
   { nome: "Presidente Prudente" },
   { nome: "Presidente Venceslau" },
   { nome: "Promissão" },
   { nome: "Quadra" },
   { nome: "Quatá" },
   { nome: "Queiroz" },
   { nome: "Queluz" },
   { nome: "Quintana" },
   { nome: "Rafard" },
   { nome: "Rancharia" },
   { nome: "Redenção da Serra" },
   { nome: "Regente Feijó" },
   { nome: "Reginópolis" },
   { nome: "Registro" },
   { nome: "Restinga" },
   { nome: "Ribeira" },
   { nome: "Ribeirão Bonito" },
   { nome: "Ribeirão Branco" },
   { nome: "Ribeirão Corrente" },
   { nome: "Ribeirão do Sul" },
   { nome: "Ribeirão dos Índios" },
   { nome: "Ribeirão Grande" },
   { nome: "Ribeirão Pires" },
   { nome: "Ribeirão Preto" },
   { nome: "Rifaina" },
   { nome: "Rincão" },
   { nome: "Rinópolis" },
   { nome: "Rio Claro" },
   { nome: "Rio das Pedras" },
   { nome: "Rio Grande da Serra" },
   { nome: "Riolândia" },
   { nome: "Riversul" },
   { nome: "Rosana" },
   { nome: "Roseira" },
   { nome: "Rubiácea" },
   { nome: "Rubinéia" },
   { nome: "Sabino" },
   { nome: "Sagres" },
   { nome: "Sales" },
   { nome: "Sales Oliveira" },
   { nome: "Salesópolis" },
   { nome: "Salmourão" },
   { nome: "Saltinho" },
   { nome: "Salto" },
   { nome: "Salto de Pirapora" },
   { nome: "Salto Grande" },
   { nome: "Sandovalina" },
   { nome: "Santa Adélia" },
   { nome: "Santa Albertina" },
   { nome: "Santa Bárbara d'Oeste" },
   { nome: "Santa Branca" },
   { nome: "Santa Clara d'Oeste" },
   { nome: "Santa Cruz da Conceição" },
   { nome: "Santa Cruz da Esperança" },
   { nome: "Santa Cruz das Palmeiras" },
   { nome: "Santa Cruz do Rio Pardo" },
   { nome: "Santa Ernestina" },
   { nome: "Santa Fé do Sul" },
   { nome: "Santa Gertrudes" },
   { nome: "Santa Isabel" },
   { nome: "Santa Lúcia" },
   { nome: "Santa Maria da Serra" },
   { nome: "Santa Mercedes" },
   { nome: "Santa Rita d'Oeste" },
   { nome: "Santa Rita do Passa Quatro" },
   { nome: "Santa Rosa de Viterbo" },
   { nome: "Santa Salete" },
   { nome: "Santana da Ponte Pensa" },
   { nome: "Santana de Parnaíba" },
   { nome: "Santo Anastácio" },
   { nome: "Santo André" },
   { nome: "Santo Antônio da Alegria" },
   { nome: "Santo Antônio de Posse" },
   { nome: "Santo Antônio do Aracanguá" },
   { nome: "Santo Antônio do Jardim" },
   { nome: "Santo Antônio do Pinhal" },
   { nome: "Santo Expedito" },
   { nome: "Santópolis do Aguapeí" },
   { nome: "Santos" },
   { nome: "São Bento do Sapucaí" },
   { nome: "São Bernardo do Campo" },
   { nome: "São Caetano do Sul" },
   { nome: "São Carlos" },
   { nome: "São Francisco" },
   { nome: "São João da Boa Vista" },
   { nome: "São João das Duas Pontes" },
   { nome: "São João de Iracema" },
   { nome: "São João do Pau d'Alho" },
   { nome: "São Joaquim da Barra" },
   { nome: "São José da Bela Vista" },
   { nome: "São José do Barreiro" },
   { nome: "São José do Rio Pardo" },
   { nome: "São José do Rio Preto" },
   { nome: "São José dos Campos" },
   { nome: "São Lourenço da Serra" },
   { nome: "São Luís do Paraitinga" },
   { nome: "São Manuel" },
   { nome: "São Miguel Arcanjo" },
   { nome: "São Paulo" },
   { nome: "São Pedro" },
   { nome: "São Pedro do Turvo" },
   { nome: "São Roque" },
   { nome: "São Sebastião" },
   { nome: "São Sebastião da Grama" },
   { nome: "São Simão" },
   { nome: "São Vicente" },
   { nome: "Sarapuí" },
   { nome: "Sarutaiá" },
   { nome: "Sebastianópolis do Sul" },
   { nome: "Serra Azul" },
   { nome: "Serra Negra" },
   { nome: "Serrana" },
   { nome: "Sertãozinho" },
   { nome: "Sete Barras" },
   { nome: "Severínia" },
   { nome: "Silveiras" },
   { nome: "Socorro" },
   { nome: "Sorocaba" },
   { nome: "Sud Mennucci" },
   { nome: "Sumaré" },
   { nome: "Suzanápolis" },
   { nome: "Suzano" },
   { nome: "Tabapuã" },
   { nome: "Tabatinga" },
   { nome: "Taboão da Serra" },
   { nome: "Taciba" },
   { nome: "Taguaí" },
   { nome: "Taiaçu" },
   { nome: "Taiúva" },
   { nome: "Tambaú" },
   { nome: "Tanabi" },
   { nome: "Tapiraí" },
   { nome: "Tapiratiba" },
   { nome: "Taquaral" },
   { nome: "Taquaritinga" },
   { nome: "Taquarituba" },
   { nome: "Taquarivaí" },
   { nome: "Tarabai" },
   { nome: "Tarumã" },
   { nome: "Tatuí" },
   { nome: "Taubaté" },
   { nome: "Tejupá" },
   { nome: "Teodoro Sampaio" },
   { nome: "Terra Roxa" },
   { nome: "Tietê" },
   { nome: "Timburi" },
   { nome: "Torre de Pedra" },
   { nome: "Torrinha" },
   { nome: "Trabiju" },
   { nome: "Tremembé" },
   { nome: "Três Fronteiras" },
   { nome: "Tuiuti" },
   { nome: "Tupã" },
   { nome: "Tupi Paulista" },
   { nome: "Turiúba" },
   { nome: "Turmalina" },
   { nome: "Ubarana" },
   { nome: "Ubatuba" },
   { nome: "Ubirajara" },
   { nome: "Uchoa" },
   { nome: "União Paulista" },
   { nome: "Urânia" },
   { nome: "Uru" },
   { nome: "Urupês" },
   { nome: "Valentim Gentil" },
   { nome: "Valinhos" },
   { nome: "Valparaíso" },
   { nome: "Vargem" },
   { nome: "Vargem Grande do Sul" },
   { nome: "Vargem Grande Paulista" },
   { nome: "Várzea Paulista" },
   { nome: "Vera Cruz" },
   { nome: "Vinhedo" },
   { nome: "Viradouro" },
   { nome: "Vista Alegre do Alto" },
   { nome: "Vitória Brasil" },
   { nome: "Votorantim" },
   { nome: "Votuporanga" },
   { nome: "Zacarias" }
  ]
)