TO = Estado.find_by_sigla("TO")
TO.cidades.create(
  [
   { nome: "Abreulândia" },
   { nome: "Aguiarnópolis" },
   { nome: "Aliança do Tocantins" },
   { nome: "Almas" },
   { nome: "Alvorada" },
   { nome: "Ananás" },
   { nome: "Angico" },
   { nome: "Aparecida do Rio Negro" },
   { nome: "Aragominas" },
   { nome: "Araguacema" },
   { nome: "Araguaçu" },
   { nome: "Araguaína" },
   { nome: "Araguanã" },
   { nome: "Araguatins" },
   { nome: "Arapoema" },
   { nome: "Arraias" },
   { nome: "Augustinópolis" },
   { nome: "Aurora do Tocantins" },
   { nome: "Axixá do Tocantins" },
   { nome: "Babaçulândia" },
   { nome: "Bandeirantes do Tocantins" },
   { nome: "Barra do Ouro" },
   { nome: "Barrolândia" },
   { nome: "Bernardo Sayão" },
   { nome: "Bom Jesus do Tocantins" },
   { nome: "Brasilândia do Tocantins" },
   { nome: "Brejinho de Nazaré" },
   { nome: "Buriti do Tocantins" },
   { nome: "Cachoeirinha" },
   { nome: "Campos Lindos" },
   { nome: "Cariri do Tocantins" },
   { nome: "Carmolândia" },
   { nome: "Carrasco Bonito" },
   { nome: "Caseara" },
   { nome: "Centenário" },
   { nome: "Chapada da Natividade" },
   { nome: "Chapada de Areia" },
   { nome: "Colinas do Tocantins" },
   { nome: "Colméia" },
   { nome: "Combinado" },
   { nome: "Conceição do Tocantins" },
   { nome: "Couto Magalhães" },
   { nome: "Cristalândia" },
   { nome: "Crixás do Tocantins" },
   { nome: "Darcinópolis" },
   { nome: "Dianópolis" },
   { nome: "Divinópolis do Tocantins" },
   { nome: "Dois Irmãos do Tocantins" },
   { nome: "Dueré" },
   { nome: "Esperantina" },
   { nome: "Fátima" },
   { nome: "Figueirópolis" },
   { nome: "Filadélfia" },
   { nome: "Formoso do Araguaia" },
   { nome: "Fortaleza do Tabocão" },
   { nome: "Goianorte" },
   { nome: "Goiatins" },
   { nome: "Guaraí" },
   { nome: "Gurupi" },
   { nome: "Ipueiras" },
   { nome: "Itacajá" },
   { nome: "Itaguatins" },
   { nome: "Itapiratins" },
   { nome: "Itaporã do Tocantins" },
   { nome: "Jaú do Tocantins" },
   { nome: "Juarina" },
   { nome: "Lagoa da Confusão" },
   { nome: "Lagoa do Tocantins" },
   { nome: "Lajeado" },
   { nome: "Lavandeira" },
   { nome: "Lizarda" },
   { nome: "Luzinópolis" },
   { nome: "Marianópolis do Tocantins" },
   { nome: "Mateiros" },
   { nome: "Maurilândia do Tocantins" },
   { nome: "Miracema do Tocantins" },
   { nome: "Miranorte" },
   { nome: "Monte do Carmo" },
   { nome: "Monte Santo do Tocantins" },
   { nome: "Muricilândia" },
   { nome: "Natividade" },
   { nome: "Nazaré" },
   { nome: "Nova Olinda" },
   { nome: "Nova Rosalândia" },
   { nome: "Novo Acordo" },
   { nome: "Novo Alegre" },
   { nome: "Novo Jardim" },
   { nome: "Oliveira de Fátima" },
   { nome: "Palmas" },
   { nome: "Palmeirante" },
   { nome: "Palmeiras do Tocantins" },
   { nome: "Palmeirópolis" },
   { nome: "Paraíso do Tocantins" },
   { nome: "Paranã" },
   { nome: "Pau d'Arco" },
   { nome: "Pedro Afonso" },
   { nome: "Peixe" },
   { nome: "Pequizeiro" },
   { nome: "Pindorama do Tocantins" },
   { nome: "Piraquê" },
   { nome: "Pium" },
   { nome: "Ponte Alta do Bom Jesus" },
   { nome: "Ponte Alta do Tocantins" },
   { nome: "Porto Alegre do Tocantins" },
   { nome: "Porto Nacional" },
   { nome: "Praia Norte" },
   { nome: "Presidente Kennedy" },
   { nome: "Pugmil" },
   { nome: "Recursolândia" },
   { nome: "Riachinho" },
   { nome: "Rio da Conceição" },
   { nome: "Rio dos Bois" },
   { nome: "Rio Sono" },
   { nome: "Sampaio" },
   { nome: "Sandolândia" },
   { nome: "Santa Fé do Araguaia" },
   { nome: "Santa Maria do Tocantins" },
   { nome: "Santa Rita do Tocantins" },
   { nome: "Santa Rosa do Tocantins" },
   { nome: "Santa Tereza do Tocantins" },
   { nome: "Santa Terezinha do Tocantins" },
   { nome: "São Bento do Tocantins" },
   { nome: "São Félix do Tocantins" },
   { nome: "São Miguel do Tocantins" },
   { nome: "São Salvador do Tocantins" },
   { nome: "São Sebastião do Tocantins" },
   { nome: "São Valério" },
   { nome: "Silvanópolis" },
   { nome: "Sítio Novo do Tocantins" },
   { nome: "Sucupira" },
   { nome: "Taguatinga" },
   { nome: "Taipas do Tocantins" },
   { nome: "Talismã" },
   { nome: "Tocantínia" },
   { nome: "Tocantinópolis" },
   { nome: "Tupirama" },
   { nome: "Tupiratins" },
   { nome: "Wanderlândia" },
   { nome: "Xambioá" }
  ]
)