Estado.create!([
  {nome: "Acre", sigla: "AC"},
  {nome: "Alagoas", sigla: "AL"},
  {nome: "Amapá", sigla: "AP"},
  {nome: "Amazonas", sigla: "AM"},
  {nome: "Bahia", sigla: "BA"},
  {nome: "Ceará", sigla: "CE"},
  {nome: "Distrito Federal", sigla: "DF"},
  {nome: "Espírito Santo", sigla: "ES"},
  {nome: "Goiás", sigla: "GO"},
  {nome: "Maranhão", sigla: "MA"},
  {nome: "Mato Grosso", sigla: "MT"},
  {nome: "Mato Grosso do Sul", sigla: "MS"},
  {nome: "Minas Gerais", sigla: "MG"},
  {nome: "Pará", sigla: "PA"},
  {nome: "Paraíba", sigla: "PB"},
  {nome: "Paraná", sigla: "PR"},
  {nome: "Pernambuco", sigla: "PE"},
  {nome: "Piauí", sigla: "PI"},
  {nome: "Rio de Janeiro", sigla: "RJ"},
  {nome: "Rio Grande do Norte", sigla: "RN"},
  {nome: "Rio Grande do Sul", sigla: "RS"},
  {nome: "Rondônia", sigla: "RO"},
  {nome: "Roraima", sigla: "RR"},
  {nome: "Santa Catarina", sigla: "SC"},
  {nome: "São Paulo", sigla: "SP"},
  {nome: "Sergipe", sigla: "SE"},
  {nome: "Tocantins", sigla: "TO"}
])

Acre = Estado.find_by_sigla("AC")
Acre.cidades.create(
  [
    {"nome": "Acrelândia"},
    {"nome": "Assis Brasil"},
    {"nome": "Brasiléia"},
    {"nome": "Bujari"},
    {"nome": "Capixaba"},
    {"nome": "Cruzeiro do Sul"},
    {"nome": "Epitaciolândia"},
    {"nome": "Feijó"},
    {"nome": "Jordão"},
    {"nome": "Mâncio Lima"},
    {"nome": "Manoel Urbano"},
    {"nome": "Marechal Thaumaturgo"},
    {"nome": "Plácido de Castro"},
    {"nome": "Porto Acre"},
    {"nome": "Porto Walter"},
    {"nome": "Rio Branco"},
    {"nome": "Rodrigues Alves"},
    {"nome": "Santa Rosa do Purus"},
    {"nome": "Sena Madureira"},
    {"nome": "Senador Guiomard"},
    {"nome": "Tarauacá"},
    {"nome": "Xapuri"}
  ]
)

Alagoas = Estado.find_by_sigla("AL")
Alagoas.cidades.create(
  [
    { "nome": "Água Branca" },
    { "nome": "Anadia" },
    { "nome": "Arapiraca" },
    { "nome": "Atalaia" },
    { "nome": "Barra de Santo Antônio" },
    { "nome": "Barra de São Miguel" },
    { "nome": "Batalha" },
    { "nome": "Belém" },
    { "nome": "Belo Monte" },
    { "nome": "Boca da Mata" },
    { "nome": "Branquinha" },
    { "nome": "Cacimbinhas" },
    { "nome": "Cajueiro" },
    { "nome": "Campestre" },
    { "nome": "Campo Alegre" },
    { "nome": "Campo Grande" },
    { "nome": "Canapi" },
    { "nome": "Capela" },
    { "nome": "Carneiros" },
    { "nome": "Chã Preta" },
    { "nome": "Coité do Nóia" },
    { "nome": "Colônia Leopoldina" },
    { "nome": "Coqueiro Seco" },
    { "nome": "Coruripe" },
    { "nome": "Craíbas" },
    { "nome": "Delmiro Gouveia" },
    { "nome": "Dois Riachos" },
    { "nome": "Estrela de Alagoas" },
    { "nome": "Feira Grande" },
    { "nome": "Feliz Deserto" },
    { "nome": "Flexeiras" },
    { "nome": "Girau do Ponciano" },
    { "nome": "Ibateguara" },
    { "nome": "Igaci" },
    { "nome": "Igreja Nova" },
    { "nome": "Inhapi" },
    { "nome": "Jacaré dos Homens" },
    { "nome": "Jacuípe" },
    { "nome": "Japaratinga" },
    { "nome": "Jaramataia" },
    { "nome": "Jequiá da Praia" },
    { "nome": "Joaquim Gomes" },
    { "nome": "Jundiá" },
    { "nome": "Junqueiro" },
    { "nome": "Lagoa da Canoa" },
    { "nome": "Limoeiro de Anadia" },
    { "nome": "Maceió" },
    { "nome": "Major Isidoro" },
    { "nome": "Mar Vermelho" },
    { "nome": "Maragogi" },
    { "nome": "Maravilha" },
    { "nome": "Marechal Deodoro" },
    { "nome": "Maribondo" },
    { "nome": "Mata Grande" },
    { "nome": "Matriz de Camaragibe" },
    { "nome": "Messias" },
    { "nome": "Minador do Negrão" },
    { "nome": "Monteirópolis" },
    { "nome": "Murici" },
    { "nome": "Novo Lino" },
    { "nome": "Olho d'Água das Flores" },
    { "nome": "Olho d'Água do Casado" },
    { "nome": "Olho d'Água Grande" },
    { "nome": "Olivença" },
    { "nome": "Ouro Branco" },
    { "nome": "Palestina" },
    { "nome": "Palmeira dos Índios" },
    { "nome": "Pão de Açúcar" },
    { "nome": "Pariconha" },
    { "nome": "Paripueira" },
    { "nome": "Passo de Camaragibe" },
    { "nome": "Paulo Jacinto" },
    { "nome": "Penedo" },
    { "nome": "Piaçabuçu" },
    { "nome": "Pilar" },
    { "nome": "Pindoba" },
    { "nome": "Piranhas" },
    { "nome": "Poço das Trincheiras" },
    { "nome": "Porto Calvo" },
    { "nome": "Porto de Pedras" },
    { "nome": "Porto Real do Colégio" },
    { "nome": "Quebrangulo" },
    { "nome": "Rio Largo" },
    { "nome": "Roteiro" },
    { "nome": "Santa Luzia do Norte" },
    { "nome": "Santana do Ipanema" },
    { "nome": "Santana do Mundaú" },
    { "nome": "São Brás" },
    { "nome": "São José da Laje" },
    { "nome": "São José da Tapera" },
    { "nome": "São Luís do Quitunde" },
    { "nome": "São Miguel dos Campos" },
    { "nome": "São Miguel dos Milagres" },
    { "nome": "São Sebastião" },
    { "nome": "Satuba" },
    { "nome": "Senador Rui Palmeira" },
    { "nome": "Tanque d'Arca" },
    { "nome": "Taquarana" },
    { "nome": "Teotônio Vilela" },
    { "nome": "Traipu" },
    { "nome": "União dos Palmares" },
    { "nome": "Viçosa" }
  ]
)

Amapa = Estado.find_by_sigla("AP")
Amapa.cidades.create(
  [
    { "nome": "Amapá" },
    { "nome": "Calçoene" },
    { "nome": "Cutias" },
    { "nome": "Ferreira Gomes" },
    { "nome": "Itaubal" },
    { "nome": "Laranjal do Jari" },
    { "nome": "Macapá" },
    { "nome": "Mazagão" },
    { "nome": "Oiapoque" },
    { "nome": "Pedra Branca do Amapari" },
    { "nome": "Porto Grande" },
    { "nome": "Pracuúba" },
    { "nome": "Santana" },
    { "nome": "Serra do Navio" },
    { "nome": "Tartarugalzinho" },
    { "nome": "Vitória do Jari" }
  ]
)

Amazonas = Estado.find_by_sigla("AP")
Amazonas.cidades.create(
  [
   { "nome": "Alvarães" },
   { "nome": "Amaturá" },
   { "nome": "Anamã" },
   { "nome": "Anori" },
   { "nome": "Apuí" },
   { "nome": "Atalaia do Norte" },
   { "nome": "Autazes" },
   { "nome": "Barcelos" },
   { "nome": "Barreirinha" },
   { "nome": "Benjamin Constant" },
   { "nome": "Beruri" },
   { "nome": "Boa Vista do Ramos" },
   { "nome": "Boca do Acre" },
   { "nome": "Borba" },
   { "nome": "Caapiranga" },
   { "nome": "Canutama" },
   { "nome": "Carauari" },
   { "nome": "Careiro" },
   { "nome": "Careiro da Várzea" },
   { "nome": "Coari" },
   { "nome": "Codajás" },
   { "nome": "Eirunepé" },
   { "nome": "Envira" },
   { "nome": "Fonte Boa" },
   { "nome": "Guajará" },
   { "nome": "Humaitá" },
   { "nome": "Ipixuna" },
   { "nome": "Iranduba" },
   { "nome": "Itacoatiara" },
   { "nome": "Itamarati" },
   { "nome": "Itapiranga" },
   { "nome": "Japurá" },
   { "nome": "Juruá" },
   { "nome": "Jutaí" },
   { "nome": "Lábrea" },
   { "nome": "Manacapuru" },
   { "nome": "Manaquiri" },
   { "nome": "Manaus" },
   { "nome": "Manicoré" },
   { "nome": "Maraã" },
   { "nome": "Maués" },
   { "nome": "Nhamundá" },
   { "nome": "Nova Olinda do Norte" },
   { "nome": "Novo Airão" },
   { "nome": "Novo Aripuanã" },
   { "nome": "Parintins" },
   { "nome": "Pauini" },
   { "nome": "Presidente Figueiredo" },
   { "nome": "Rio Preto da Eva" },
   { "nome": "Santa Isabel do Rio Negro" },
   { "nome": "Santo Antônio do Içá" },
   { "nome": "São Gabriel da Cachoeira" },
   { "nome": "São Paulo de Olivença" },
   { "nome": "São Sebastião do Uatumã" },
   { "nome": "Silves" },
   { "nome": "Tabatinga" },
   { "nome": "Tapauá" },
   { "nome": "Tefé" },
   { "nome": "Tonantins" },
   { "nome": "Uarini" },
   { "nome": "Urucará" },
   { "nome": "Urucurituba" }
  ]
)